<?php

namespace App\Support;

class KarnatakaMandiDirectory
{
    /**
     * Complete Standard Karnataka APMC and Board Market Directory (KRAMA Aligned).
     * Covers all APMC yards across all 31 Karnataka districts.
     *
     * @return array<int, array<string, mixed>>
     */
    public static function all(): array
    {
        return [
            // ==========================================
            // SHIVAMOGGA (ಶಿವಮೊಗ್ಗ)
            // ==========================================
            [
                'name' => 'Shivamogga APMC',
                'name_kn' => 'ಶಿವಮೊಗ್ಗ ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_SHI',
                'district' => 'Shivamogga',
                'market_type' => 'APMC',
                'lat' => 13.9310,
                'lon' => 75.5700,
                'address' => 'APMC Market Yard, B.H. Road, Shivamogga',
                'raw_aliases' => ['SHIVAMOGGA', 'SHIMOGA', 'SHIVAMOGGA APMC'],
            ],
            [
                'name' => 'Thirthahalli APMC',
                'name_kn' => 'ತೀರ್ಥಹಳ್ಳಿ ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_THI',
                'district' => 'Shivamogga',
                'market_type' => 'APMC',
                'lat' => 13.7000,
                'lon' => 75.2400,
                'address' => 'APMC Market Yard, Thirthahalli, Shivamogga District',
                'raw_aliases' => ['TIRTHAHALLI', 'THIRTHAHALLI', 'TIRTHAHALLI APMC'],
            ],
            [
                'name' => 'Sagara APMC',
                'name_kn' => 'ಸಾಗರ ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_SAG',
                'district' => 'Shivamogga',
                'market_type' => 'APMC',
                'lat' => 14.1670,
                'lon' => 75.0330,
                'address' => 'APMC Yard, Sagara, Shivamogga District',
                'raw_aliases' => ['SAGAR', 'SAGARA', 'SAGARA APMC'],
            ],
            [
                'name' => 'Shikaripura APMC',
                'name_kn' => 'ಶಿಕಾರಿಪುರ ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_SKP',
                'district' => 'Shivamogga',
                'market_type' => 'APMC',
                'lat' => 14.2690,
                'lon' => 75.3530,
                'address' => 'APMC Yard, Shikaripura, Shivamogga District',
                'raw_aliases' => ['SHIKARIPUR', 'SHIKARIPURA', 'SHIKARIPUR APMC'],
            ],
            [
                'name' => 'Bhadravathi APMC',
                'name_kn' => 'ಭದ್ರಾವತಿ ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_BDV',
                'district' => 'Shivamogga',
                'market_type' => 'APMC',
                'lat' => 13.8400,
                'lon' => 75.7000,
                'address' => 'APMC Yard, Bhadravathi, Shivamogga District',
                'raw_aliases' => ['BHADRAVATHI', 'BHADRAVATI', 'BHADRAVATHI APMC'],
            ],
            [
                'name' => 'Soraba APMC',
                'name_kn' => 'ಸೊರಬ ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_SRB',
                'district' => 'Shivamogga',
                'market_type' => 'APMC',
                'lat' => 14.3800,
                'lon' => 75.1000,
                'address' => 'APMC Yard, Soraba, Shivamogga District',
                'raw_aliases' => ['SORABHA', 'SORABA', 'SORABHA APMC'],
            ],
            [
                'name' => 'Hosanagar APMC',
                'name_kn' => 'ಹೊಸನಗರ ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_HSN_S',
                'district' => 'Shivamogga',
                'market_type' => 'APMC',
                'lat' => 13.9200,
                'lon' => 75.0700,
                'address' => 'APMC Yard, Hosanagar, Shivamogga District',
                'raw_aliases' => ['HOSANAGAR', 'HOSANAGARA', 'HOSANAGAR APMC'],
            ],

            // ==========================================
            // DAVANAGERE (ದಾವಣಗೆರೆ)
            // ==========================================
            [
                'name' => 'Davanagere APMC',
                'name_kn' => 'ದಾವಣಗೆರೆ ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_DVG',
                'district' => 'Davanagere',
                'market_type' => 'APMC',
                'lat' => 14.4644,
                'lon' => 75.9218,
                'address' => 'APMC Market Yard, Davanagere',
                'raw_aliases' => ['DAVANAGERE', 'DAVANGERE', 'DAVANAGERE APMC'],
            ],
            [
                'name' => 'Channagiri APMC',
                'name_kn' => 'ಚನ್ನಗಿರಿ ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_CNG',
                'district' => 'Davanagere',
                'market_type' => 'APMC',
                'lat' => 14.0270,
                'lon' => 75.9260,
                'address' => 'APMC Yard, Main Road, Channagiri',
                'raw_aliases' => ['CHANNAGIRI', 'CHANNAGIRI APMC'],
            ],
            [
                'name' => 'Harihara APMC',
                'name_kn' => 'ಹರಿಹರ ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_HRH',
                'district' => 'Davanagere',
                'market_type' => 'APMC',
                'lat' => 14.5120,
                'lon' => 75.8050,
                'address' => 'APMC Yard, Harihara, Davanagere District',
                'raw_aliases' => ['HARIHARA', 'HARIHAR', 'HARIHARA APMC'],
            ],
            [
                'name' => 'Honnali APMC',
                'name_kn' => 'ಹೊನ್ನಾಳಿ ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_HNL',
                'district' => 'Davanagere',
                'market_type' => 'APMC',
                'lat' => 14.2440,
                'lon' => 75.6440,
                'address' => 'APMC Yard, Honnali, Davanagere District',
                'raw_aliases' => ['HONNALI', 'HONNALI APMC'],
            ],
            [
                'name' => 'Jagalur APMC',
                'name_kn' => 'ಜಗಳೂರು ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_JGL',
                'district' => 'Davanagere',
                'market_type' => 'APMC',
                'lat' => 14.5200,
                'lon' => 76.3500,
                'address' => 'APMC Yard, Jagalur, Davanagere District',
                'raw_aliases' => ['JAGALUR', 'JAGALUR APMC'],
            ],
            [
                'name' => 'Nyamathi APMC',
                'name_kn' => 'ನ್ಯಾಮತಿ ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_NMT',
                'district' => 'Davanagere',
                'market_type' => 'APMC',
                'lat' => 14.1500,
                'lon' => 75.5800,
                'address' => 'APMC Yard, Nyamathi, Davanagere District',
                'raw_aliases' => ['NYAMATHI', 'NYAMATHI APMC'],
            ],

            // ==========================================
            // UTTARA KANNADA (ಉತ್ತರ ಕನ್ನಡ)
            // ==========================================
            [
                'name' => 'Sirsi APMC (TSS)',
                'name_kn' => 'ಶಿರಸಿ ಎಪಿಎಂಸಿ (ಟಿಎಸ್ಎಸ್)',
                'code' => 'KA_APMC_SRS',
                'district' => 'Uttara Kannada',
                'market_type' => 'APMC',
                'lat' => 14.6195,
                'lon' => 74.8354,
                'address' => 'TSS APMC Yard, Sirsi, Uttara Kannada',
                'raw_aliases' => ['SIRSI', 'SIRSI (TSS)', 'SIRSI APMC', 'TSS SIRSI'],
            ],
            [
                'name' => 'Yellapur APMC',
                'name_kn' => 'ಯಲ್ಲಾಪುರ ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_YLP',
                'district' => 'Uttara Kannada',
                'market_type' => 'APMC',
                'lat' => 14.9640,
                'lon' => 74.7120,
                'address' => 'APMC Yard, Yellapur, Uttara Kannada',
                'raw_aliases' => ['YELLAPURA', 'YELLAPUR', 'YELLAPURA APMC'],
            ],
            [
                'name' => 'Kumta APMC',
                'name_kn' => 'ಕುಮಟಾ ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_KMT',
                'district' => 'Uttara Kannada',
                'market_type' => 'APMC',
                'lat' => 14.4270,
                'lon' => 74.4080,
                'address' => 'APMC Yard, Kumta, Uttara Kannada',
                'raw_aliases' => ['KUMTA', 'KUMTA APMC'],
            ],
            [
                'name' => 'Siddapur APMC',
                'name_kn' => 'ಸಿದ್ಧಾಪುರ ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_SDP',
                'district' => 'Uttara Kannada',
                'market_type' => 'APMC',
                'lat' => 14.3400,
                'lon' => 74.8900,
                'address' => 'APMC Yard, Siddapur, Uttara Kannada',
                'raw_aliases' => ['SIDDAPURA', 'SIDDAPUR', 'SIDDAPURA APMC'],
            ],
            [
                'name' => 'Mundgod APMC',
                'name_kn' => 'ಮುಂಡಗೋಡ ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_MDG_U',
                'district' => 'Uttara Kannada',
                'market_type' => 'APMC',
                'lat' => 14.9700,
                'lon' => 75.0300,
                'address' => 'APMC Yard, Mundgod, Uttara Kannada',
                'raw_aliases' => ['MUNDAGOD', 'MUNDGOD', 'MUNDAGOD APMC'],
            ],
            [
                'name' => 'Honnavar APMC',
                'name_kn' => 'ಹೊನ್ನಾವರ ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_HNV',
                'district' => 'Uttara Kannada',
                'market_type' => 'APMC',
                'lat' => 14.2800,
                'lon' => 74.4500,
                'address' => 'APMC Yard, Honnavar, Uttara Kannada',
                'raw_aliases' => ['HONNAVAR', 'HONNAVAR APMC'],
            ],
            [
                'name' => 'Haliyal APMC',
                'name_kn' => 'ಹಳಿಯಾಳ ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_HLY_U',
                'district' => 'Uttara Kannada',
                'market_type' => 'APMC',
                'lat' => 15.3300,
                'lon' => 74.7600,
                'address' => 'APMC Yard, Haliyal, Uttara Kannada',
                'raw_aliases' => ['HALIYALA', 'HALIYAL', 'HALIYALA APMC'],
            ],
            [
                'name' => 'Karwar APMC',
                'name_kn' => 'ಕಾರವಾರ ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_KRW',
                'district' => 'Uttara Kannada',
                'market_type' => 'APMC',
                'lat' => 14.8100,
                'lon' => 74.1300,
                'address' => 'APMC Yard, Karwar, Uttara Kannada',
                'raw_aliases' => ['KARWAR', 'KARWAR APMC'],
            ],
            [
                'name' => 'Bhatkal APMC',
                'name_kn' => 'ಭಟ್ಕಳ ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_BTK',
                'district' => 'Uttara Kannada',
                'market_type' => 'APMC',
                'lat' => 13.9700,
                'lon' => 74.5500,
                'address' => 'APMC Yard, Bhatkal, Uttara Kannada',
                'raw_aliases' => ['BHATKAL', 'BHATKAL APMC'],
            ],
            [
                'name' => 'Ankola APMC',
                'name_kn' => 'ಅಂಕೋಲಾ ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_ANK',
                'district' => 'Uttara Kannada',
                'market_type' => 'APMC',
                'lat' => 14.6600,
                'lon' => 74.3000,
                'address' => 'APMC Yard, Ankola, Uttara Kannada',
                'raw_aliases' => ['ANKOLA', 'ANKOLA APMC'],
            ],

            // ==========================================
            // DAKSHINA KANNADA (ದಕ್ಷಿಣ ಕನ್ನಡ)
            // ==========================================
            [
                'name' => 'Mangaluru APMC (Baikampady)',
                'name_kn' => 'ಮಂಗಳೂರು ಎಪಿಎಂಸಿ (ಬೈಕಂಪಾಡಿ)',
                'code' => 'KA_APMC_MNG',
                'district' => 'Dakshina Kannada',
                'market_type' => 'APMC',
                'lat' => 12.9467,
                'lon' => 74.8122,
                'address' => 'APMC Yard, Baikampady, Mangaluru',
                'raw_aliases' => ['MANGALURU', 'MANGALORE', 'MANGALURU APMC'],
            ],
            [
                'name' => 'Bantwal APMC',
                'name_kn' => 'ಬಂಟ್ವಾಳ ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_BNT',
                'district' => 'Dakshina Kannada',
                'market_type' => 'APMC',
                'lat' => 12.8940,
                'lon' => 75.0330,
                'address' => 'APMC Yard, B.C. Road, Bantwal',
                'raw_aliases' => ['BANTWALA', 'BANTWAL', 'BANTWALA APMC'],
            ],
            [
                'name' => 'Puttur APMC',
                'name_kn' => 'ಪುತ್ತೂರು ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_PTR',
                'district' => 'Dakshina Kannada',
                'market_type' => 'APMC',
                'lat' => 12.7667,
                'lon' => 75.2000,
                'address' => 'APMC Yard, Puttur, Dakshina Kannada',
                'raw_aliases' => ['PUTTUR', 'PUTTUR APMC'],
            ],
            [
                'name' => 'Sullia APMC',
                'name_kn' => 'ಸುಳ್ಯ ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_SLA',
                'district' => 'Dakshina Kannada',
                'market_type' => 'APMC',
                'lat' => 12.5600,
                'lon' => 75.3900,
                'address' => 'APMC Yard, Sullia, Dakshina Kannada',
                'raw_aliases' => ['SULYA', 'SULLIA', 'SULYA APMC'],
            ],
            [
                'name' => 'Belthangadi APMC',
                'name_kn' => 'ಬೆಳ್ತಂಗಡಿ ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_BTG',
                'district' => 'Dakshina Kannada',
                'market_type' => 'APMC',
                'lat' => 13.0000,
                'lon' => 75.2600,
                'address' => 'APMC Yard, Belthangadi, Dakshina Kannada',
                'raw_aliases' => ['BELTHANGADI', 'BELTHANGADY', 'BELTHANGADI APMC'],
            ],

            // ==========================================
            // UDUPI (ಉಡುಪಿ)
            // ==========================================
            [
                'name' => 'Udupi APMC',
                'name_kn' => 'ಉಡುಪಿ ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_UDP',
                'district' => 'Udupi',
                'market_type' => 'APMC',
                'lat' => 13.3420,
                'lon' => 74.7450,
                'address' => 'APMC Market, Adi Udupi',
                'raw_aliases' => ['UDIPI', 'UDUPI', 'UDIPI APMC'],
            ],
            [
                'name' => 'Kundapura APMC',
                'name_kn' => 'ಕುಂದಾಪುರ ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_KND',
                'district' => 'Udupi',
                'market_type' => 'APMC',
                'lat' => 13.6280,
                'lon' => 74.6950,
                'address' => 'APMC Yard, Kundapura, Udupi District',
                'raw_aliases' => ['KUNDAPUR', 'KUNDAPURA', 'KUNDAPUR APMC'],
            ],
            [
                'name' => 'Karkala APMC',
                'name_kn' => 'ಕಾರ್ಕಳ ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_KRK',
                'district' => 'Udupi',
                'market_type' => 'APMC',
                'lat' => 13.2100,
                'lon' => 74.9900,
                'address' => 'APMC Yard, Karkala, Udupi District',
                'raw_aliases' => ['KARKALA', 'KARKALA APMC'],
            ],

            // ==========================================
            // CHIKKAMAGALURU (ಚಿಕ್ಕಮಗಳೂರು)
            // ==========================================
            [
                'name' => 'Chikkamagaluru APMC',
                'name_kn' => 'ಚಿಕ್ಕಮಗಳೂರು ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_CKM',
                'district' => 'Chikkamagaluru',
                'market_type' => 'APMC',
                'lat' => 13.3161,
                'lon' => 75.7720,
                'address' => 'APMC Yard, Chikkamagaluru',
                'raw_aliases' => ['CHIKKAMAGALURU', 'CHIKMAGALUR', 'CHIKKAMAGALURU APMC'],
            ],
            [
                'name' => 'Kadur APMC',
                'name_kn' => 'ಕಡೂರು ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_KDR',
                'district' => 'Chikkamagaluru',
                'market_type' => 'APMC',
                'lat' => 13.5530,
                'lon' => 76.0120,
                'address' => 'APMC Yard, Kadur, Chikkamagaluru District',
                'raw_aliases' => ['KADUR', 'KADUR APMC'],
            ],
            [
                'name' => 'Tarikere APMC',
                'name_kn' => 'ತರೀಕೆರೆ ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_TRK',
                'district' => 'Chikkamagaluru',
                'market_type' => 'APMC',
                'lat' => 13.7130,
                'lon' => 75.8150,
                'address' => 'APMC Yard, Tarikere, Chikkamagaluru District',
                'raw_aliases' => ['TARIKERE', 'TARIKERE APMC'],
            ],
            [
                'name' => 'Mudigere APMC',
                'name_kn' => 'ಮೂಡಿಗೆರೆ ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_MDG',
                'district' => 'Chikkamagaluru',
                'market_type' => 'APMC',
                'lat' => 13.1360,
                'lon' => 75.6400,
                'address' => 'APMC Yard, Mudigere, Chikkamagaluru District',
                'raw_aliases' => ['MUDIGERE', 'MUDIGERE APMC'],
            ],
            [
                'name' => 'Koppa APMC',
                'name_kn' => 'ಕೊಪ್ಪ ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_KPA',
                'district' => 'Chikkamagaluru',
                'market_type' => 'APMC',
                'lat' => 13.5300,
                'lon' => 75.3600,
                'address' => 'APMC Yard, Koppa, Chikkamagaluru District',
                'raw_aliases' => ['KOPPA', 'KOPPA APMC'],
            ],

            // ==========================================
            // HASSAN (ಹಾಸನ)
            // ==========================================
            [
                'name' => 'Hassan APMC',
                'name_kn' => 'ಹಾಸನ ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_HSN',
                'district' => 'Hassan',
                'market_type' => 'APMC',
                'lat' => 13.0033,
                'lon' => 76.1004,
                'address' => 'APMC Yard, B.M. Road, Hassan',
                'raw_aliases' => ['HASSAN', 'HASSAN APMC'],
            ],
            [
                'name' => 'Arsikere APMC',
                'name_kn' => 'ಅರಸೀಕೆರೆ ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_ASK',
                'district' => 'Hassan',
                'market_type' => 'APMC',
                'lat' => 13.3138,
                'lon' => 76.2570,
                'address' => 'APMC Yard, Arsikere, Hassan District',
                'raw_aliases' => ['ARSIKERE', 'ARASIKERE', 'ARSIKERE APMC'],
            ],
            [
                'name' => 'Channarayapatna APMC',
                'name_kn' => 'ಚನ್ನರಾಯಪಟ್ಟಣ ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_CRP',
                'district' => 'Hassan',
                'market_type' => 'APMC',
                'lat' => 12.9050,
                'lon' => 76.3880,
                'address' => 'APMC Yard, Channarayapatna, Hassan District',
                'raw_aliases' => ['C.R.PATNA', 'CHANNARAYAPATNA', 'C.R.PATNA APMC'],
            ],
            [
                'name' => 'Sakleshpur APMC',
                'name_kn' => 'ಸಕಲೇಶಪುರ ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_SKL',
                'district' => 'Hassan',
                'market_type' => 'APMC',
                'lat' => 12.9430,
                'lon' => 75.7870,
                'address' => 'APMC Yard, Sakleshpur, Hassan District',
                'raw_aliases' => ['SAKLESHPUR', 'SAKLESHPURA', 'SAKLESHPUR APMC'],
            ],
            [
                'name' => 'Belur APMC',
                'name_kn' => 'ಬೇಲೂರು ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_BLR_H',
                'district' => 'Hassan',
                'market_type' => 'APMC',
                'lat' => 13.1600,
                'lon' => 75.8600,
                'address' => 'APMC Yard, Belur, Hassan District',
                'raw_aliases' => ['BELUR', 'BELUR APMC'],
            ],
            [
                'name' => 'Arakalgud APMC',
                'name_kn' => 'ಅರಕಲಗೂಡು ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_AKG',
                'district' => 'Hassan',
                'market_type' => 'APMC',
                'lat' => 12.7700,
                'lon' => 76.0600,
                'address' => 'APMC Yard, Arakalgud, Hassan District',
                'raw_aliases' => ['ARAKALGUD', 'ARAKALAGUDU', 'ARAKALGUD APMC'],
            ],
            [
                'name' => 'Holenarasipura APMC',
                'name_kn' => 'ಹೊಳೆನರಸೀಪುರ ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_HNP',
                'district' => 'Hassan',
                'market_type' => 'APMC',
                'lat' => 12.7900,
                'lon' => 76.2400,
                'address' => 'APMC Yard, Holenarasipura, Hassan District',
                'raw_aliases' => ['HOLENARASIPUR', 'HOLENARASIPURA', 'HOLENARASIPUR APMC'],
            ],

            // ==========================================
            // TUMAKURU (ತುಮಕೂರು)
            // ==========================================
            [
                'name' => 'Tumakuru APMC',
                'name_kn' => 'ತುಮಕೂರು ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_TMK',
                'district' => 'Tumakuru',
                'market_type' => 'APMC',
                'lat' => 13.3409,
                'lon' => 77.1010,
                'address' => 'APMC Yard, Batawadi, Tumakuru',
                'raw_aliases' => ['TUMAKURU', 'TUMKUR', 'TUMAKURU APMC'],
            ],
            [
                'name' => 'Tiptur APMC',
                'name_kn' => 'ತಿಪಟೂರು ಎಪಿಎಂಸಿ (ಕೊಬ್ಬರಿ ಮಾರುಕಟ್ಟೆ)',
                'code' => 'KA_APMC_TPT',
                'district' => 'Tumakuru',
                'market_type' => 'APMC',
                'lat' => 13.2570,
                'lon' => 76.4780,
                'address' => 'APMC Yard, Tiptur (Copra Capital)',
                'raw_aliases' => ['TIPTUR', 'TIPTUR APMC'],
            ],
            [
                'name' => 'Sira APMC',
                'name_kn' => 'ಶಿರಾ ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_SRA',
                'district' => 'Tumakuru',
                'market_type' => 'APMC',
                'lat' => 13.7400,
                'lon' => 76.9000,
                'address' => 'APMC Yard, Sira, Tumakuru District',
                'raw_aliases' => ['SIRA', 'SIRA APMC'],
            ],
            [
                'name' => 'Gubbi APMC',
                'name_kn' => 'ಗುಬ್ಬಿ ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_GBI',
                'district' => 'Tumakuru',
                'market_type' => 'APMC',
                'lat' => 13.3100,
                'lon' => 76.9400,
                'address' => 'APMC Yard, Gubbi, Tumakuru District',
                'raw_aliases' => ['GUBBI', 'GUBBI APMC'],
            ],
            [
                'name' => 'Turuvekere APMC',
                'name_kn' => 'ತುರುವೇಕೆರೆ ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_TRV',
                'district' => 'Tumakuru',
                'market_type' => 'APMC',
                'lat' => 13.1600,
                'lon' => 76.6700,
                'address' => 'APMC Yard, Turuvekere, Tumakuru District',
                'raw_aliases' => ['TURUVEKERE', 'TURUVEKERE APMC'],
            ],
            [
                'name' => 'Huliyar APMC',
                'name_kn' => 'ಹುಳಿಯಾರು ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_HLY_T',
                'district' => 'Tumakuru',
                'market_type' => 'APMC',
                'lat' => 13.5800,
                'lon' => 76.5400,
                'address' => 'APMC Yard, Huliyar, C.N.Halli Taluk',
                'raw_aliases' => ['HULIYAR', 'HULIYAR APMC'],
            ],

            // ==========================================
            // CHITRADURGA (ಚಿತ್ರದುರ್ಗ)
            // ==========================================
            [
                'name' => 'Chitradurga APMC',
                'name_kn' => 'ಚಿತ್ರದುರ್ಗ ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_CTA',
                'district' => 'Chitradurga',
                'market_type' => 'APMC',
                'lat' => 14.2251,
                'lon' => 76.4020,
                'address' => 'APMC Yard, Chitradurga',
                'raw_aliases' => ['CHITRADURGA', 'CHITRADURGA APMC'],
            ],
            [
                'name' => 'Challakere APMC',
                'name_kn' => 'ಚಳ್ಳಕೆರೆ ಎಪಿಎಂಸಿ (ಎಣ್ಣೆಬೀಜ ಮಾರುಕಟ್ಟೆ)',
                'code' => 'KA_APMC_CLK',
                'district' => 'Chitradurga',
                'market_type' => 'APMC',
                'lat' => 14.3130,
                'lon' => 76.6510,
                'address' => 'APMC Yard, Challakere (Oil Seeds City)',
                'raw_aliases' => ['CHALLAKERE', 'CHALLAKERE APMC'],
            ],
            [
                'name' => 'Hiriyur APMC',
                'name_kn' => 'ಹಿರಿಯೂರು ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_HRY',
                'district' => 'Chitradurga',
                'market_type' => 'APMC',
                'lat' => 13.9450,
                'lon' => 76.6180,
                'address' => 'APMC Yard, Hiriyur, Chitradurga District',
                'raw_aliases' => ['HIRIYUR', 'HIRIYUR APMC'],
            ],
            [
                'name' => 'Hosadurga APMC',
                'name_kn' => 'ಹೊಸದುರ್ಗ ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_HSD',
                'district' => 'Chitradurga',
                'market_type' => 'APMC',
                'lat' => 13.7990,
                'lon' => 76.2850,
                'address' => 'APMC Yard, Hosadurga, Chitradurga District',
                'raw_aliases' => ['HOSADURGA', 'HOSADURGA APMC'],
            ],
            [
                'name' => 'Holalkere APMC',
                'name_kn' => 'ಹೊಳಲ್ಕೆರೆ ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_HLK',
                'district' => 'Chitradurga',
                'market_type' => 'APMC',
                'lat' => 14.0320,
                'lon' => 76.1830,
                'address' => 'APMC Yard, Holalkere, Chitradurga District',
                'raw_aliases' => ['HOLALKERE', 'HOLALKERE APMC'],
            ],

            // ==========================================
            // KOLAR (ಕೋಲಾರ)
            // ==========================================
            [
                'name' => 'Kolar APMC (Tomato Market)',
                'name_kn' => 'ಕೋಲಾರ ಎಪಿಎಂಸಿ (ಟೊಮೆಟೊ ಮಾರುಕಟ್ಟೆ)',
                'code' => 'KA_APMC_KLR',
                'district' => 'Kolar',
                'market_type' => 'APMC',
                'lat' => 13.1380,
                'lon' => 78.1350,
                'address' => 'APMC Yard, Kolar (Asia Second Largest Tomato Mandi)',
                'raw_aliases' => ['KOLAR', 'KOLAR APMC'],
            ],
            [
                'name' => 'Bangarpet APMC',
                'name_kn' => 'ಬಂಗಾರಪೇಟೆ ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_BPT',
                'district' => 'Kolar',
                'market_type' => 'APMC',
                'lat' => 12.9800,
                'lon' => 78.2000,
                'address' => 'APMC Yard, Bangarpet, Kolar District',
                'raw_aliases' => ['BANGARPET', 'BANGARAPETE', 'BANGARPET APMC'],
            ],
            [
                'name' => 'Malur APMC',
                'name_kn' => 'ಮಾಲೂರು ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_MLR',
                'district' => 'Kolar',
                'market_type' => 'APMC',
                'lat' => 13.0000,
                'lon' => 77.9400,
                'address' => 'APMC Yard, Malur, Kolar District',
                'raw_aliases' => ['MALUR', 'MALUR APMC'],
            ],
            [
                'name' => 'Mulbagal APMC',
                'name_kn' => 'ಮುಳಬಾಗಿಲು ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_MLB',
                'district' => 'Kolar',
                'market_type' => 'APMC',
                'lat' => 13.1600,
                'lon' => 78.3900,
                'address' => 'APMC Yard, Mulbagal, Kolar District',
                'raw_aliases' => ['MULBAGAL', 'MULABAGILU', 'MULBAGAL APMC'],
            ],
            [
                'name' => 'Srinivaspur APMC',
                'name_kn' => 'ಶ್ರೀನಿವಾಸಪುರ ಎಪಿಎಂಸಿ (ಮಾವು ಮಾರುಕಟ್ಟೆ)',
                'code' => 'KA_APMC_SVP',
                'district' => 'Kolar',
                'market_type' => 'APMC',
                'lat' => 13.3400,
                'lon' => 78.2100,
                'address' => 'APMC Yard, Srinivaspur (Mango Capital)',
                'raw_aliases' => ['SRINIVASPUR', 'SRINIVASAPURA', 'SRINIVASPUR APMC'],
            ],

            // ==========================================
            // CHIKKABALLAPURA (ಚಿಕ್ಕಬಳ್ಳಾಪುರ)
            // ==========================================
            [
                'name' => 'Chikkaballapura APMC',
                'name_kn' => 'ಚಿಕ್ಕಬಳ್ಳಾಪುರ ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_CKB',
                'district' => 'Chikkaballapura',
                'market_type' => 'APMC',
                'lat' => 13.4355,
                'lon' => 77.7315,
                'address' => 'APMC Yard, Chikkaballapura',
                'raw_aliases' => ['CHICKBALLAPUR', 'CHIKKABALLAPUR', 'CHICKBALLAPUR APMC'],
            ],
            [
                'name' => 'Chintamani APMC',
                'name_kn' => 'ಚಿಂತಾಮಣಿ ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_CTM',
                'district' => 'Chikkaballapura',
                'market_type' => 'APMC',
                'lat' => 13.4000,
                'lon' => 78.0600,
                'address' => 'APMC Yard, Chintamani, Chikkaballapura District',
                'raw_aliases' => ['CHINTAMANI', 'CHINTHAMANI', 'CHINTAMANI APMC'],
            ],
            [
                'name' => 'Gowribidnur APMC',
                'name_kn' => 'ಗೌರಿಬಿದನೂರು ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_GBN',
                'district' => 'Chikkaballapura',
                'market_type' => 'APMC',
                'lat' => 13.6100,
                'lon' => 77.5200,
                'address' => 'APMC Yard, Gowribidnur, Chikkaballapura District',
                'raw_aliases' => ['GOWRIBIDNUR', 'GAURIBIDANUR', 'GOWRIBIDNUR APMC'],
            ],
            [
                'name' => 'Bagepalli APMC',
                'name_kn' => 'ಬಾಗೇಪಲ್ಲಿ ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_BGP',
                'district' => 'Chikkaballapura',
                'market_type' => 'APMC',
                'lat' => 13.7800,
                'lon' => 77.7900,
                'address' => 'APMC Yard, Bagepalli, Chikkaballapura District',
                'raw_aliases' => ['BAGEPALLI', 'BAGEPALLI APMC'],
            ],
            [
                'name' => 'Sidlaghatta APMC',
                'name_kn' => 'ಶಿಡ್ಲಘಟ್ಟ ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_SDG',
                'district' => 'Chikkaballapura',
                'market_type' => 'APMC',
                'lat' => 13.3900,
                'lon' => 77.8600,
                'address' => 'APMC Yard, Sidlaghatta, Chikkaballapura District',
                'raw_aliases' => ['SIDLAGHATTA', 'SHIDLAGHATTA', 'SIDLAGHATTA APMC'],
            ],

            // ==========================================
            // BENGALURU URBAN & RURAL (ಬೆಂಗಳೂರು)
            // ==========================================
            [
                'name' => 'Yeshwanthpur APMC',
                'name_kn' => 'ಯಶವಂತಪುರ ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_YPR',
                'district' => 'Bengaluru Urban',
                'market_type' => 'APMC',
                'lat' => 13.0238,
                'lon' => 77.5458,
                'address' => 'APMC Yard, Yeshwanthpur, Bengaluru',
                'raw_aliases' => ['YESHWANTHPUR', 'YESHWANTHPUR APMC'],
            ],
            [
                'name' => 'Binny Mill (F&V)',
                'name_kn' => 'ಬಿನ್ನಿ ಮಿಲ್ (ಹಣ್ಣು ಮತ್ತು ತರಕಾರಿ)',
                'code' => 'KA_APMC_BNM',
                'district' => 'Bengaluru Urban',
                'market_type' => 'Specialized Market',
                'lat' => 12.9667,
                'lon' => 77.5667,
                'address' => 'Binny Mill Market, Cottonpet, Bengaluru',
                'raw_aliases' => ['BINNY MILL (F&V)', 'BINNY MILL', 'BINNY MILLS'],
            ],
            [
                'name' => 'Bengaluru APMC',
                'name_kn' => 'ಬೆಂಗಳೂರು ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_BLR',
                'district' => 'Bengaluru Urban',
                'market_type' => 'APMC',
                'lat' => 12.9716,
                'lon' => 77.5946,
                'address' => 'APMC Market Yard, Bengaluru Urban',
                'raw_aliases' => ['BENGALURU', 'BANGALORE', 'BENGALURU APMC'],
            ],
            [
                'name' => 'Doddaballapur APMC',
                'name_kn' => 'ದೊಡ್ಡಬಳ್ಳಾಪುರ ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_DBP',
                'district' => 'Bengaluru Rural',
                'market_type' => 'APMC',
                'lat' => 13.2929,
                'lon' => 77.5428,
                'address' => 'APMC Yard, Doddaballapur, Bengaluru Rural',
                'raw_aliases' => ['DODDABALLAPUR', 'DODDABALLAPURA', 'DODDABALLAPUR APMC'],
            ],
            [
                'name' => 'Hoskote APMC',
                'name_kn' => 'ಹೊಸಕೋಟೆ ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_HSK',
                'district' => 'Bengaluru Rural',
                'market_type' => 'APMC',
                'lat' => 13.0700,
                'lon' => 77.8000,
                'address' => 'APMC Yard, Hoskote, Bengaluru Rural',
                'raw_aliases' => ['HOSKOTE', 'HOSAKOTE', 'HOSKOTE APMC'],
            ],

            // ==========================================
            // MANDYA (ಮಂಡ್ಯ)
            // ==========================================
            [
                'name' => 'Mandya APMC',
                'name_kn' => 'ಮಂಡ್ಯ ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_MDY',
                'district' => 'Mandya',
                'market_type' => 'APMC',
                'lat' => 12.5218,
                'lon' => 76.8951,
                'address' => 'APMC Yard, Mandya',
                'raw_aliases' => ['MANDYA', 'MANDYA APMC'],
            ],
            [
                'name' => 'Maddur APMC',
                'name_kn' => 'ಮದ್ದೂರು ಎಪಿಎಂಸಿ (ಎಳನೀರು ಮಾರುಕಟ್ಟೆ)',
                'code' => 'KA_APMC_MDR',
                'district' => 'Mandya',
                'market_type' => 'APMC',
                'lat' => 12.5840,
                'lon' => 77.0450,
                'address' => 'APMC Yard, Maddur (Tender Coconut Hub)',
                'raw_aliases' => ['MADDUR', 'MADDUR APMC'],
            ],
            [
                'name' => 'Malavalli APMC',
                'name_kn' => 'ಮಳವಳ್ಳಿ ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_MLV',
                'district' => 'Mandya',
                'market_type' => 'APMC',
                'lat' => 12.3800,
                'lon' => 77.0600,
                'address' => 'APMC Yard, Malavalli, Mandya District',
                'raw_aliases' => ['MALAVALLI', 'MALAVALLI APMC'],
            ],
            [
                'name' => 'Pandavapura APMC',
                'name_kn' => 'ಪಾಂಡವಪುರ ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_PDP',
                'district' => 'Mandya',
                'market_type' => 'APMC',
                'lat' => 12.5000,
                'lon' => 76.6700,
                'address' => 'APMC Yard, Pandavapura, Mandya District',
                'raw_aliases' => ['PANDAVAPURA', 'PANDAVAPURA APMC'],
            ],
            [
                'name' => 'Krishnarajapete APMC',
                'name_kn' => 'ಕೃಷ್ಣರಾಜಪೇಟೆ ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_KRP',
                'district' => 'Mandya',
                'market_type' => 'APMC',
                'lat' => 12.6600,
                'lon' => 76.4900,
                'address' => 'APMC Yard, K.R.Pet, Mandya District',
                'raw_aliases' => ['K.R.PET', 'KRISHNARAJAPET', 'K.R.PET APMC'],
            ],
            [
                'name' => 'Nagamangala APMC',
                'name_kn' => 'ನಾಗಮಂಗಲ ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_NGM',
                'district' => 'Mandya',
                'market_type' => 'APMC',
                'lat' => 12.8200,
                'lon' => 76.7600,
                'address' => 'APMC Yard, Nagamangala, Mandya District',
                'raw_aliases' => ['NAGAMANGALA', 'NAGAMANGALA APMC'],
            ],
            [
                'name' => 'Srirangapatna APMC',
                'name_kn' => 'ಶ್ರೀರಂಗಪಟ್ಟಣ ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_SRP',
                'district' => 'Mandya',
                'market_type' => 'APMC',
                'lat' => 12.4200,
                'lon' => 76.6900,
                'address' => 'APMC Yard, Srirangapatna, Mandya District',
                'raw_aliases' => ['SRIRANGAPATNA', 'SRIRANGAPATTANA', 'SRIRANGAPATNA APMC'],
            ],

            // ==========================================
            // MYSURU (ಮೈಸೂರು)
            // ==========================================
            [
                'name' => 'Mysuru APMC (Bandipalya)',
                'name_kn' => 'ಮೈಸೂರು ಎಪಿಎಂಸಿ (ಬಂಡಿಪಾಳ್ಯ)',
                'code' => 'KA_APMC_MYS',
                'district' => 'Mysuru',
                'market_type' => 'APMC',
                'lat' => 12.2740,
                'lon' => 76.6690,
                'address' => 'APMC Bandipalya Yard, Mysuru',
                'raw_aliases' => ['MYSURU', 'MYSORE', 'MYSURU APMC', 'BANDIPALYA'],
            ],
            [
                'name' => 'Nanjangud APMC',
                'name_kn' => 'ನಂಜನಗೂಡು ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_NJG',
                'district' => 'Mysuru',
                'market_type' => 'APMC',
                'lat' => 12.1190,
                'lon' => 76.6830,
                'address' => 'APMC Yard, Nanjangud, Mysuru District',
                'raw_aliases' => ['NANJANGUD', 'NANJANAGUDU', 'NANJANGUD APMC'],
            ],
            [
                'name' => 'Hunsur APMC',
                'name_kn' => 'ಹುಣಸೂರು ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_HNS',
                'district' => 'Mysuru',
                'market_type' => 'APMC',
                'lat' => 12.3100,
                'lon' => 76.2900,
                'address' => 'APMC Yard, Hunsur, Mysuru District',
                'raw_aliases' => ['HUNSUR', 'HUNASURU', 'HUNSUR APMC'],
            ],
            [
                'name' => 'T. Narasipura APMC',
                'name_kn' => 'ಟಿ. ನರಸೀಪುರ ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_TNP',
                'district' => 'Mysuru',
                'market_type' => 'APMC',
                'lat' => 12.2100,
                'lon' => 76.9000,
                'address' => 'APMC Yard, T.Narsipur, Mysuru District',
                'raw_aliases' => ['T.NARSIPUR', 'T.NARASIPURA', 'T.NARSIPUR APMC'],
            ],
            [
                'name' => 'Krishnarajanagara APMC',
                'name_kn' => 'ಕೆ.ಆರ್.ನಗರ ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_KRN',
                'district' => 'Mysuru',
                'market_type' => 'APMC',
                'lat' => 12.5800,
                'lon' => 76.3800,
                'address' => 'APMC Yard, K.R.Nagar, Mysuru District',
                'raw_aliases' => ['K.R.NAGAR', 'KRISHNARAJANAGAR', 'K.R.NAGAR APMC'],
            ],
            [
                'name' => 'Periyapatna APMC',
                'name_kn' => 'ಪಿರಿಯಾಪಟ್ಟಣ ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_PPT',
                'district' => 'Mysuru',
                'market_type' => 'APMC',
                'lat' => 12.3400,
                'lon' => 76.1000,
                'address' => 'APMC Yard, Periyapatna, Mysuru District',
                'raw_aliases' => ['PERIYAPATNA', 'PIRIYAPATNA', 'PERIYAPATNA APMC'],
            ],

            // ==========================================
            // CHAMARAJANAGAR (ಚಾಮರಾಜನಗರ)
            // ==========================================
            [
                'name' => 'Chamarajanagar APMC',
                'name_kn' => 'ಚಾಮರಾಜನಗರ ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_CRN',
                'district' => 'Chamarajanagar',
                'market_type' => 'APMC',
                'lat' => 11.9261,
                'lon' => 76.9437,
                'address' => 'APMC Yard, Chamarajanagar',
                'raw_aliases' => ['C.R.NAGAR', 'CHAMARAJANAGAR', 'C.R.NAGAR APMC'],
            ],
            [
                'name' => 'Kollegal APMC',
                'name_kn' => 'ಕೊಳ್ಳೇಗಾಲ ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_KLG',
                'district' => 'Chamarajanagar',
                'market_type' => 'APMC',
                'lat' => 12.1550,
                'lon' => 77.1120,
                'address' => 'APMC Yard, Kollegal, Chamarajanagar District',
                'raw_aliases' => ['KOLLEGAL', 'KOLLEGALA', 'KOLLEGAL APMC'],
            ],
            [
                'name' => 'Gundlupet APMC',
                'name_kn' => 'ಗುಂಡ್ಲುಪೇಟೆ ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_GLP',
                'district' => 'Chamarajanagar',
                'market_type' => 'APMC',
                'lat' => 11.8100,
                'lon' => 76.6900,
                'address' => 'APMC Yard, Gundlupet, Chamarajanagar District',
                'raw_aliases' => ['GUNDLUPET', 'GUNDLUPETE', 'GUNDLUPET APMC'],
            ],
            [
                'name' => 'Hanur APMC',
                'name_kn' => 'ಹನೂರು ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_HNR',
                'district' => 'Chamarajanagar',
                'market_type' => 'APMC',
                'lat' => 12.0900,
                'lon' => 77.3000,
                'address' => 'APMC Yard, Hanur, Chamarajanagar District',
                'raw_aliases' => ['HANUR', 'HANUR APMC'],
            ],
            [
                'name' => 'Santhemarahalli APMC',
                'name_kn' => 'ಸಂತೆಮರಹಳ್ಳಿ ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_SMH',
                'district' => 'Chamarajanagar',
                'market_type' => 'APMC',
                'lat' => 11.9800,
                'lon' => 76.9900,
                'address' => 'APMC Yard, Santhemarahalli, Chamarajanagar District',
                'raw_aliases' => ['SANTHESARGUR', 'SANTHEMARAHALLI', 'SANTHESARGUR APMC'],
            ],

            // ==========================================
            // RAMANAGARA (ರಾಮನಗರ)
            // ==========================================
            [
                'name' => 'Ramanagara Silk Cocoon Market',
                'name_kn' => 'ರಾಮನಗರ ರೇಷ್ಮೆ ಗೂಡು ಮಾರುಕಟ್ಟೆ',
                'code' => 'KA_MKT_RAM',
                'district' => 'Ramanagara',
                'market_type' => 'Specialized Market',
                'lat' => 12.7214,
                'lon' => 77.2807,
                'address' => 'Government Silk Cocoon Market, Ramanagara',
                'raw_aliases' => ['RAMANAGARA SILK', 'RAMANAGARA SILK COCOON'],
            ],
            [
                'name' => 'Ramanagara APMC',
                'name_kn' => 'ರಾಮನಗರ ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_RMN',
                'district' => 'Ramanagara',
                'market_type' => 'APMC',
                'lat' => 12.7214,
                'lon' => 77.2807,
                'address' => 'APMC Yard, Ramanagara',
                'raw_aliases' => ['RAMANAGARA', 'RAMANAGARAM', 'RAMANAGARA APMC'],
            ],
            [
                'name' => 'Channapatna APMC',
                'name_kn' => 'ಚನ್ನಪಟ್ಟಣ ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_CPT',
                'district' => 'Ramanagara',
                'market_type' => 'APMC',
                'lat' => 12.6500,
                'lon' => 77.2000,
                'address' => 'APMC Yard, Channapatna, Ramanagara District',
                'raw_aliases' => ['CHANNAPATNA', 'CHANNAPATTANA', 'CHANNAPATNA APMC'],
            ],
            [
                'name' => 'Kanakapura APMC',
                'name_kn' => 'ಕನಕಪುರ ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_KKP',
                'district' => 'Ramanagara',
                'market_type' => 'APMC',
                'lat' => 12.5500,
                'lon' => 77.4100,
                'address' => 'APMC Yard, Kanakapura, Ramanagara District',
                'raw_aliases' => ['KANAKAPURA', 'KANAKAPURA APMC'],
            ],

            // ==========================================
            // DHARWAD (ಧಾರವಾಡ)
            // ==========================================
            [
                'name' => 'Hubballi APMC (Amaragol)',
                'name_kn' => 'ಹುಬ್ಬಳ್ಳಿ ಎಪಿಎಂಸಿ (ಅಮರಗೋಳ)',
                'code' => 'KA_APMC_HBL',
                'district' => 'Dharwad',
                'market_type' => 'APMC',
                'lat' => 15.3950,
                'lon' => 75.0930,
                'address' => 'Amaragol APMC Yard, Hubballi',
                'raw_aliases' => ['HUBBALLI', 'HUBLI', 'AMARAGOL', 'HUBBALLI APMC'],
            ],
            [
                'name' => 'Dharwad APMC',
                'name_kn' => 'ಧಾರವಾಡ ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_DWR',
                'district' => 'Dharwad',
                'market_type' => 'APMC',
                'lat' => 15.4589,
                'lon' => 75.0078,
                'address' => 'APMC Yard, Dharwad',
                'raw_aliases' => ['DHARWAR', 'DHARWAD', 'DHARWAR APMC'],
            ],
            [
                'name' => 'Annigeri APMC',
                'name_kn' => 'ಅಣ್ಣಿಗೇರಿ ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_ANG',
                'district' => 'Dharwad',
                'market_type' => 'APMC',
                'lat' => 15.4300,
                'lon' => 75.4300,
                'address' => 'APMC Yard, Annigeri, Dharwad District',
                'raw_aliases' => ['ANNIGERI', 'ANNIGERI APMC'],
            ],
            [
                'name' => 'Kundgol APMC',
                'name_kn' => 'ಕುಂದಗೋಳ ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_KDG',
                'district' => 'Dharwad',
                'market_type' => 'APMC',
                'lat' => 15.2500,
                'lon' => 75.2500,
                'address' => 'APMC Yard, Kundgol, Dharwad District',
                'raw_aliases' => ['KUNDGOL', 'KUNDAGOL', 'KUNDGOL APMC'],
            ],
            [
                'name' => 'Kalghatgi APMC',
                'name_kn' => 'ಕಲಘಟಗಿ ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_KLG_D',
                'district' => 'Dharwad',
                'market_type' => 'APMC',
                'lat' => 15.1800,
                'lon' => 74.9700,
                'address' => 'APMC Yard, Kalghatgi, Dharwad District',
                'raw_aliases' => ['KALGHATGI', 'KALAGHATAGI', 'KALGHATGI APMC'],
            ],

            // ==========================================
            // GADAG (ಗದಗ)
            // ==========================================
            [
                'name' => 'Gadag APMC',
                'name_kn' => 'ಗದಗ ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_GDG',
                'district' => 'Gadag',
                'market_type' => 'APMC',
                'lat' => 15.4319,
                'lon' => 75.6358,
                'address' => 'APMC Yard, Gadag',
                'raw_aliases' => ['GADAG', 'GADAG APMC'],
            ],
            [
                'name' => 'Nargund APMC',
                'name_kn' => 'ನರಗುಂದ ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_NRG',
                'district' => 'Gadag',
                'market_type' => 'APMC',
                'lat' => 15.7200,
                'lon' => 75.3900,
                'address' => 'APMC Yard, Nargund, Gadag District',
                'raw_aliases' => ['NARGUND', 'NARAGUNDA', 'NARGUND APMC'],
            ],
            [
                'name' => 'Laxmeshwar APMC',
                'name_kn' => 'ಲಕ್ಷ್ಮೇಶ್ವರ ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_LXM',
                'district' => 'Gadag',
                'market_type' => 'APMC',
                'lat' => 15.1300,
                'lon' => 75.4700,
                'address' => 'APMC Yard, Laxmeshwar, Gadag District',
                'raw_aliases' => ['LAXMESHWAR', 'LAKSHMESHWAR', 'LAXMESHWAR APMC'],
            ],
            [
                'name' => 'Mundargi APMC',
                'name_kn' => 'ಮುಂಡರಗಿ ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_MND',
                'district' => 'Gadag',
                'market_type' => 'APMC',
                'lat' => 15.2100,
                'lon' => 75.8900,
                'address' => 'APMC Yard, Mundargi, Gadag District',
                'raw_aliases' => ['MUNDARGI', 'MUNDARAGI', 'MUNDARGI APMC'],
            ],
            [
                'name' => 'Ron APMC',
                'name_kn' => 'ರೋಣ ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_RON',
                'district' => 'Gadag',
                'market_type' => 'APMC',
                'lat' => 15.7000,
                'lon' => 75.7300,
                'address' => 'APMC Yard, Ron, Gadag District',
                'raw_aliases' => ['RON', 'RON APMC'],
            ],

            // ==========================================
            // HAVERI (ಹಾವೇರಿ)
            // ==========================================
            [
                'name' => 'Haveri APMC',
                'name_kn' => 'ಹಾವೇರಿ ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_HVR',
                'district' => 'Haveri',
                'market_type' => 'APMC',
                'lat' => 14.7955,
                'lon' => 75.3991,
                'address' => 'APMC Yard, Haveri',
                'raw_aliases' => ['HAVERI', 'HAVERI APMC'],
            ],
            [
                'name' => 'Ranebennur APMC',
                'name_kn' => 'ರಾಣೆಬೆನ್ನೂರು ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_RBN',
                'district' => 'Haveri',
                'market_type' => 'APMC',
                'lat' => 14.6230,
                'lon' => 75.6210,
                'address' => 'APMC Yard, Ranebennur, Haveri District',
                'raw_aliases' => ['RANIBENNUR', 'RANEBENNUR', 'RANIBENNUR APMC'],
            ],
            [
                'name' => 'Byadgi APMC',
                'name_kn' => 'ಬ್ಯಾಡಗಿ ಎಪಿಎಂಸಿ (ಮೆಣಸಿನಕಾಯಿ ಮಾರುಕಟ್ಟೆ)',
                'code' => 'KA_APMC_BDG',
                'district' => 'Haveri',
                'market_type' => 'APMC',
                'lat' => 14.6800,
                'lon' => 75.4900,
                'address' => 'APMC Yard, Byadgi (Asia Renowned Chilli Market)',
                'raw_aliases' => ['BYADGI', 'BYADAGI', 'BYADGI APMC'],
            ],
            [
                'name' => 'Hangal APMC',
                'name_kn' => 'ಹಾನಗಲ್ ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_HGL',
                'district' => 'Haveri',
                'market_type' => 'APMC',
                'lat' => 14.7600,
                'lon' => 75.1300,
                'address' => 'APMC Yard, Hangal, Haveri District',
                'raw_aliases' => ['HANGAL', 'HANGAL APMC'],
            ],
            [
                'name' => 'Hirekerur APMC',
                'name_kn' => 'ಹಿರೇಕೆರೂರು ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_HKR_H',
                'district' => 'Haveri',
                'market_type' => 'APMC',
                'lat' => 14.4600,
                'lon' => 75.3900,
                'address' => 'APMC Yard, Hirekerur, Haveri District',
                'raw_aliases' => ['HIREKERUR', 'HIREKERUR APMC'],
            ],
            [
                'name' => 'Shiggaon APMC',
                'name_kn' => 'ಶಿಗ್ಗಾವಿ ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_SGN',
                'district' => 'Haveri',
                'market_type' => 'APMC',
                'lat' => 14.9900,
                'lon' => 75.2300,
                'address' => 'APMC Yard, Shiggaon, Haveri District',
                'raw_aliases' => ['SHIGGAON', 'SHIGGAVI', 'SHIGGAON APMC'],
            ],
            [
                'name' => 'Savanur APMC',
                'name_kn' => 'ಸವಣೂರು ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_SVN',
                'district' => 'Haveri',
                'market_type' => 'APMC',
                'lat' => 14.9700,
                'lon' => 75.3400,
                'address' => 'APMC Yard, Savanur, Haveri District',
                'raw_aliases' => ['SAVANUR', 'SAVANUR APMC'],
            ],

            // ==========================================
            // BELAGAVI (ಬೆಳಗಾವಿ)
            // ==========================================
            [
                'name' => 'Belagavi APMC',
                'name_kn' => 'ಬೆಳಗಾವಿ ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_BLG',
                'district' => 'Belagavi',
                'market_type' => 'APMC',
                'lat' => 15.8497,
                'lon' => 74.4977,
                'address' => 'APMC Yard, Belagavi',
                'raw_aliases' => ['BELAGAVI', 'BELGAUM', 'BELAGAVI APMC'],
            ],
            [
                'name' => 'Bailhongal APMC',
                'name_kn' => 'ಬೈಲಹೊಂಗಲ ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_BLH',
                'district' => 'Belagavi',
                'market_type' => 'APMC',
                'lat' => 15.8167,
                'lon' => 74.8667,
                'address' => 'APMC Yard, Bailhongal, Belagavi District',
                'raw_aliases' => ['BAILHONGAL', 'BAILAHONGALA', 'BAILHONGAL APMC'],
            ],
            [
                'name' => 'Gokak APMC',
                'name_kn' => 'ಗೋಕಾಕ್ ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_GKK',
                'district' => 'Belagavi',
                'market_type' => 'APMC',
                'lat' => 16.1667,
                'lon' => 74.8333,
                'address' => 'APMC Yard, Gokak, Belagavi District',
                'raw_aliases' => ['GOKAK', 'GOKAK APMC'],
            ],
            [
                'name' => 'Athani APMC',
                'name_kn' => 'ಅಥಣಿ ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_ATN',
                'district' => 'Belagavi',
                'market_type' => 'APMC',
                'lat' => 16.7330,
                'lon' => 75.0670,
                'address' => 'APMC Yard, Athani, Belagavi District',
                'raw_aliases' => ['ATHANI', 'ATHANI APMC'],
            ],
            [
                'name' => 'Ramdurg APMC',
                'name_kn' => 'ರಾಮದುರ್ಗ ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_RMD',
                'district' => 'Belagavi',
                'market_type' => 'APMC',
                'lat' => 15.9500,
                'lon' => 75.3000,
                'address' => 'APMC Yard, Ramdurg, Belagavi District',
                'raw_aliases' => ['RAMDURGA', 'RAMDURG', 'RAMDURGA APMC'],
            ],
            [
                'name' => 'Savadatti APMC',
                'name_kn' => 'ಸವದತ್ತಿ ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_SVD',
                'district' => 'Belagavi',
                'market_type' => 'APMC',
                'lat' => 15.7700,
                'lon' => 75.1200,
                'address' => 'APMC Yard, Savadatti, Belagavi District',
                'raw_aliases' => ['SAVADATTI', 'SAUNDATTI', 'SAVADATTI APMC'],
            ],
            [
                'name' => 'Sankeshwar APMC',
                'name_kn' => 'ಸಂಕೇಶ್ವರ ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_SNK',
                'district' => 'Belagavi',
                'market_type' => 'APMC',
                'lat' => 16.2600,
                'lon' => 74.4800,
                'address' => 'APMC Yard, Sankeshwar, Belagavi District',
                'raw_aliases' => ['SANKESHWAR', 'SANKESHWAR APMC'],
            ],
            [
                'name' => 'Nippani APMC',
                'name_kn' => 'ನಿಪ್ಪಾಣಿ ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_NPN',
                'district' => 'Belagavi',
                'market_type' => 'APMC',
                'lat' => 16.4000,
                'lon' => 74.3800,
                'address' => 'APMC Yard, Nippani, Belagavi District',
                'raw_aliases' => ['NIPPANI', 'NIPANI', 'NIPPANI APMC'],
            ],
            [
                'name' => 'Kudchi APMC',
                'name_kn' => 'ಕುಡಚಿ ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_KDC',
                'district' => 'Belagavi',
                'market_type' => 'APMC',
                'lat' => 16.6300,
                'lon' => 74.8500,
                'address' => 'APMC Yard, Kudchi, Belagavi District',
                'raw_aliases' => ['KUDCHI', 'KUDCHI APMC'],
            ],
            [
                'name' => 'Nandagad APMC',
                'name_kn' => 'ನಂದಗಡ ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_NDG',
                'district' => 'Belagavi',
                'market_type' => 'APMC',
                'lat' => 15.5500,
                'lon' => 74.5500,
                'address' => 'APMC Yard, Nandagad, Belagavi District',
                'raw_aliases' => ['NANDAGAD', 'NANDAGADA', 'NANDAGAD APMC'],
            ],
            [
                'name' => 'Yaragatti APMC',
                'name_kn' => 'ಯರಗಟ್ಟಿ ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_YRG',
                'district' => 'Belagavi',
                'market_type' => 'APMC',
                'lat' => 15.9300,
                'lon' => 75.0200,
                'address' => 'APMC Yard, Yaragatti, Belagavi District',
                'raw_aliases' => ['YARAGATTI', 'YARAGATTI APMC'],
            ],

            // ==========================================
            // BAGALKOTE (ಬಾಗಲಕೋಟೆ)
            // ==========================================
            [
                'name' => 'Bagalkot APMC',
                'name_kn' => 'ಬಾಗಲಕೋಟೆ ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_BGK',
                'district' => 'Bagalkote',
                'market_type' => 'APMC',
                'lat' => 16.1817,
                'lon' => 75.6958,
                'address' => 'APMC Yard, Bagalkot',
                'raw_aliases' => ['BAGALKOT', 'BAGALKOTE', 'BAGALKOT APMC'],
            ],
            [
                'name' => 'Jamkandi APMC',
                'name_kn' => 'ಜಮಖಂಡಿ ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_JMK',
                'district' => 'Bagalkote',
                'market_type' => 'APMC',
                'lat' => 16.5050,
                'lon' => 75.2950,
                'address' => 'APMC Yard, Jamkandi, Bagalkote District',
                'raw_aliases' => ['JAMKANDI', 'JAMKHANDI', 'JAMKANDI APMC'],
            ],
            [
                'name' => 'Badami APMC',
                'name_kn' => 'ಬಾದಾಮಿ ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_BDM',
                'district' => 'Bagalkote',
                'market_type' => 'APMC',
                'lat' => 15.9180,
                'lon' => 75.6760,
                'address' => 'APMC Yard, Badami, Bagalkote District',
                'raw_aliases' => ['BADAMI', 'BADAMI APMC'],
            ],
            [
                'name' => 'Hungund APMC',
                'name_kn' => 'ಹುನಗುಂದ ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_HGD',
                'district' => 'Bagalkote',
                'market_type' => 'APMC',
                'lat' => 16.0640,
                'lon' => 76.0570,
                'address' => 'APMC Yard, Hungund, Bagalkote District',
                'raw_aliases' => ['HUNGUND', 'HUNAGUNDA', 'HUNGUND APMC'],
            ],

            // ==========================================
            // VIJAYAPURA (ವಿಜಯಪುರ)
            // ==========================================
            [
                'name' => 'Vijayapura APMC',
                'name_kn' => 'ವಿಜಯಪುರ ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_VJP',
                'district' => 'Vijayapura',
                'market_type' => 'APMC',
                'lat' => 16.8302,
                'lon' => 75.7100,
                'address' => 'APMC Yard, Vijayapura',
                'raw_aliases' => ['VIJAYAPURA', 'BIJAPUR', 'VIJAYAPURA APMC'],
            ],
            [
                'name' => 'Talikote APMC',
                'name_kn' => 'ತಾಳಿಕೋಟೆ ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_TLK',
                'district' => 'Vijayapura',
                'market_type' => 'APMC',
                'lat' => 16.4800,
                'lon' => 76.3100,
                'address' => 'APMC Yard, Talikote, Vijayapura District',
                'raw_aliases' => ['TALIKOTE', 'TALIKOTI', 'TALIKOTE APMC'],
            ],
            [
                'name' => 'Sindagi APMC',
                'name_kn' => 'ಸಿಂದಗಿ ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_SDG_V',
                'district' => 'Vijayapura',
                'market_type' => 'APMC',
                'lat' => 16.9200,
                'lon' => 76.2300,
                'address' => 'APMC Yard, Sindagi, Vijayapura District',
                'raw_aliases' => ['SINDAGI', 'SINDHAGI', 'SINDAGI APMC'],
            ],

            // ==========================================
            // KALABURAGI (ಕಲಬುರಗಿ)
            // ==========================================
            [
                'name' => 'Kalaburagi APMC (Tur Market)',
                'name_kn' => 'ಕಲಬುರಗಿ ಎಪಿಎಂಸಿ (ತೊಗರಿ ಮಾರುಕಟ್ಟೆ)',
                'code' => 'KA_APMC_KLB',
                'district' => 'Kalaburagi',
                'market_type' => 'APMC',
                'lat' => 17.3297,
                'lon' => 76.8343,
                'address' => 'Nehru Gunj APMC Yard, Kalaburagi (Red Gram Capital)',
                'raw_aliases' => ['KALABURAGI', 'GULBARGA', 'NEHRU GUNJ', 'KALABURAGI APMC'],
            ],
            [
                'name' => 'Sedam APMC',
                'name_kn' => 'ಸೇಡಂ ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_SDM',
                'district' => 'Kalaburagi',
                'market_type' => 'APMC',
                'lat' => 17.1800,
                'lon' => 77.2900,
                'address' => 'APMC Yard, Sedam, Kalaburagi District',
                'raw_aliases' => ['SEDAM', 'SEDAM APMC'],
            ],
            [
                'name' => 'Chittapur APMC',
                'name_kn' => 'ಚಿತ್ತಾಪುರ ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_CTP',
                'district' => 'Kalaburagi',
                'market_type' => 'APMC',
                'lat' => 17.1200,
                'lon' => 76.9600,
                'address' => 'APMC Yard, Chittapur, Kalaburagi District',
                'raw_aliases' => ['CHITTAPURA', 'CHITTAPUR', 'CHITTAPURA APMC'],
            ],
            [
                'name' => 'Chincholi APMC',
                'name_kn' => 'ಚಿಂಚೋಳಿ ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_CNC',
                'district' => 'Kalaburagi',
                'market_type' => 'APMC',
                'lat' => 17.4700,
                'lon' => 77.4300,
                'address' => 'APMC Yard, Chincholi, Kalaburagi District',
                'raw_aliases' => ['CHINCOLI', 'CHINCHOLI', 'CHINCOLI APMC'],
            ],
            [
                'name' => 'Jevargi APMC',
                'name_kn' => 'ಜೇವರ್ಗಿ ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_JVR',
                'district' => 'Kalaburagi',
                'market_type' => 'APMC',
                'lat' => 17.0200,
                'lon' => 76.7700,
                'address' => 'APMC Yard, Jevargi, Kalaburagi District',
                'raw_aliases' => ['JEVARGI', 'JEVARAGI', 'JEVARGI APMC'],
            ],

            // ==========================================
            // BIDAR (ಬೀದರ್)
            // ==========================================
            [
                'name' => 'Bidar APMC',
                'name_kn' => 'ಬೀದರ್ ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_BDR',
                'district' => 'Bidar',
                'market_type' => 'APMC',
                'lat' => 17.9104,
                'lon' => 77.5199,
                'address' => 'APMC Yard, Bidar',
                'raw_aliases' => ['BIDAR', 'BIDAR APMC'],
            ],
            [
                'name' => 'Basavakalyana APMC',
                'name_kn' => 'ಬಸವಕಲ್ಯಾಣ ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_BSK',
                'district' => 'Bidar',
                'market_type' => 'APMC',
                'lat' => 17.8700,
                'lon' => 76.9500,
                'address' => 'APMC Yard, Basavakalyana, Bidar District',
                'raw_aliases' => ['BASAVAKALYANA', 'BASAVAKALYAN', 'BASAVAKALYANA APMC'],
            ],
            [
                'name' => 'Bhalki APMC',
                'name_kn' => 'ಭಾಲ್ಕಿ ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_BLK',
                'district' => 'Bidar',
                'market_type' => 'APMC',
                'lat' => 18.0400,
                'lon' => 77.2100,
                'address' => 'APMC Yard, Bhalki, Bidar District',
                'raw_aliases' => ['BHALKI', 'BHALKI APMC'],
            ],
            [
                'name' => 'Aurad APMC',
                'name_kn' => 'ಔರಾದ್ ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_ARD',
                'district' => 'Bidar',
                'market_type' => 'APMC',
                'lat' => 18.2500,
                'lon' => 77.4300,
                'address' => 'APMC Yard, Aurad, Bidar District',
                'raw_aliases' => ['AURAD', 'AURAD APMC'],
            ],

            // ==========================================
            // RAICHUR (ರಾಯಚೂರು)
            // ==========================================
            [
                'name' => 'Raichur APMC (Cotton & Paddy)',
                'name_kn' => 'ರಾಯಚೂರು ಎಪಿಎಂಸಿ (ಹತ್ತಿ ಮತ್ತು ಭತ್ತ)',
                'code' => 'KA_APMC_RCH',
                'district' => 'Raichur',
                'market_type' => 'APMC',
                'lat' => 16.2076,
                'lon' => 77.3463,
                'address' => 'APMC Yard, Raichur',
                'raw_aliases' => ['RAICHUR', 'RAICHUR APMC'],
            ],
            [
                'name' => 'Sindhanur APMC',
                'name_kn' => 'ಸಿಂಧನೂರು ಎಪಿಎಂಸಿ (ಭತ್ತದ ರಾಜಧಾನಿ)',
                'code' => 'KA_APMC_SDN',
                'district' => 'Raichur',
                'market_type' => 'APMC',
                'lat' => 15.7700,
                'lon' => 76.7600,
                'address' => 'APMC Yard, Sindhanur (Paddy Capital)',
                'raw_aliases' => ['SINDHANUR', 'SINDHANUR APMC'],
            ],
            [
                'name' => 'Manvi APMC',
                'name_kn' => 'ಮಾನ್ವಿ ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_MNV',
                'district' => 'Raichur',
                'market_type' => 'APMC',
                'lat' => 15.9900,
                'lon' => 77.0500,
                'address' => 'APMC Yard, Manvi, Raichur District',
                'raw_aliases' => ['MANVI', 'MANVI APMC'],
            ],
            [
                'name' => 'Lingasugur APMC',
                'name_kn' => 'ಲಿಂಗಸುಗೂರು ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_LSG',
                'district' => 'Raichur',
                'market_type' => 'APMC',
                'lat' => 16.1600,
                'lon' => 76.5200,
                'address' => 'APMC Yard, Lingasugur, Raichur District',
                'raw_aliases' => ['LINGASARGUR', 'LINGASUGUR', 'LINGASARGUR APMC'],
            ],
            [
                'name' => 'Maski APMC',
                'name_kn' => 'ಮಸ್ಕಿ ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_MSK',
                'district' => 'Raichur',
                'market_type' => 'APMC',
                'lat' => 15.9600,
                'lon' => 76.6600,
                'address' => 'APMC Yard, Maski, Raichur District',
                'raw_aliases' => ['MASKI', 'MASKI APMC'],
            ],

            // ==========================================
            // KOPPAL (ಕೊಪ್ಪಳ)
            // ==========================================
            [
                'name' => 'Koppal APMC',
                'name_kn' => 'ಕೊಪ್ಪಳ ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_KPL',
                'district' => 'Koppal',
                'market_type' => 'APMC',
                'lat' => 15.3456,
                'lon' => 76.1557,
                'address' => 'APMC Yard, Koppal',
                'raw_aliases' => ['KOPPAL', 'KOPPAL APMC'],
            ],
            [
                'name' => 'Gangavati APMC',
                'name_kn' => 'ಗಂಗಾವತಿ ಎಪಿಎಂಸಿ (ಭತ್ತದ ಮಾರುಕಟ್ಟೆ)',
                'code' => 'KA_APMC_GGV',
                'district' => 'Koppal',
                'market_type' => 'APMC',
                'lat' => 15.4300,
                'lon' => 76.5300,
                'address' => 'APMC Yard, Gangavati (Rice Bowl of Karnataka)',
                'raw_aliases' => ['GANGAVATI', 'GANGAVATHI', 'GANGAVATI APMC'],
            ],
            [
                'name' => 'Kushtagi APMC',
                'name_kn' => 'ಕುಷ್ಟಗಿ ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_KSG',
                'district' => 'Koppal',
                'market_type' => 'APMC',
                'lat' => 15.7500,
                'lon' => 76.2000,
                'address' => 'APMC Yard, Kushtagi, Koppal District',
                'raw_aliases' => ['KUSTAGI', 'KUSHTAGI', 'KUSTAGI APMC'],
            ],
            [
                'name' => 'Yelburga APMC',
                'name_kn' => 'ಯಲಬುರ್ಗಾ ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_YBG',
                'district' => 'Koppal',
                'market_type' => 'APMC',
                'lat' => 15.6300,
                'lon' => 76.0100,
                'address' => 'APMC Yard, Yelburga, Koppal District',
                'raw_aliases' => ['YELBURGA', 'YALABURGA', 'YELBURGA APMC'],
            ],
            [
                'name' => 'Kanakagiri APMC',
                'name_kn' => 'ಕನಕಗಿರಿ ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_KKG',
                'district' => 'Koppal',
                'market_type' => 'APMC',
                'lat' => 15.5700,
                'lon' => 76.4200,
                'address' => 'APMC Yard, Kanakagiri, Koppal District',
                'raw_aliases' => ['KANAKAGIRI', 'KANAKAGIRI APMC'],
            ],
            [
                'name' => 'Karatagi APMC',
                'name_kn' => 'ಕಾರಟಗಿ ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_KTG',
                'district' => 'Koppal',
                'market_type' => 'APMC',
                'lat' => 15.5700,
                'lon' => 76.6800,
                'address' => 'APMC Yard, Karatagi, Koppal District',
                'raw_aliases' => ['KARTAGI', 'KARATAGI', 'KARTAGI APMC'],
            ],

            // ==========================================
            // BALLARI (ಬಳ್ಳಾರಿ)
            // ==========================================
            [
                'name' => 'Ballari APMC',
                'name_kn' => 'ಬಳ್ಳಾರಿ ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_BAL',
                'district' => 'Ballari',
                'market_type' => 'APMC',
                'lat' => 15.1394,
                'lon' => 76.9214,
                'address' => 'APMC Yard, Ballari',
                'raw_aliases' => ['BALLARI', 'BELLARY', 'BALLARI APMC'],
            ],
            [
                'name' => 'Kampli APMC',
                'name_kn' => 'ಕಂಪ್ಲಿ ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_KMP',
                'district' => 'Ballari',
                'market_type' => 'APMC',
                'lat' => 15.4050,
                'lon' => 76.5950,
                'address' => 'APMC Yard, Kampli, Ballari District',
                'raw_aliases' => ['KAMPLI', 'KAMPLI APMC'],
            ],
            [
                'name' => 'Siruguppa APMC',
                'name_kn' => 'ಸಿರಗುಪ್ಪ ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_SGP',
                'district' => 'Ballari',
                'market_type' => 'APMC',
                'lat' => 15.6320,
                'lon' => 76.8970,
                'address' => 'APMC Yard, Siruguppa, Ballari District',
                'raw_aliases' => ['SIRAGUPPA', 'SIRUGUPPA', 'SIRAGUPPA APMC'],
            ],

            // ==========================================
            // VIJAYANAGARA (ವಿಜಯನಗರ)
            // ==========================================
            [
                'name' => 'Hosapete APMC',
                'name_kn' => 'ಹೊಸಪೇಟೆ ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_HSP',
                'district' => 'Vijayanagara',
                'market_type' => 'APMC',
                'lat' => 15.2700,
                'lon' => 76.3900,
                'address' => 'APMC Yard, Hosapete',
                'raw_aliases' => ['HOSAPETE', 'HOSPET', 'HOSAPETE APMC'],
            ],
            [
                'name' => 'Harapanahalli APMC',
                'name_kn' => 'ಹರಪನಹಳ್ಳಿ ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_HPH',
                'district' => 'Vijayanagara',
                'market_type' => 'APMC',
                'lat' => 14.7900,
                'lon' => 75.9900,
                'address' => 'APMC Yard, Harapanahalli, Vijayanagara District',
                'raw_aliases' => ['HARAPANAHALLI', 'HARAPANAHALLI APMC'],
            ],
            [
                'name' => 'Hagaribommanahalli APMC',
                'name_kn' => 'ಹಗರಿಬೊಮ್ಮನಹಳ್ಳಿ ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_HBH',
                'district' => 'Vijayanagara',
                'market_type' => 'APMC',
                'lat' => 15.0800,
                'lon' => 76.2000,
                'address' => 'APMC Yard, Hagaribommanahalli, Vijayanagara District',
                'raw_aliases' => ['HAGARI BOMMANA HALLI', 'HAGARIBOMMANAHALLI', 'H.B.HALLI'],
            ],
            [
                'name' => 'Hoovinahadagali APMC',
                'name_kn' => 'ಹೂವಿನಹಡಗಲಿ ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_HHD',
                'district' => 'Vijayanagara',
                'market_type' => 'APMC',
                'lat' => 15.0200,
                'lon' => 75.9500,
                'address' => 'APMC Yard, Hoovinahadagali, Vijayanagara District',
                'raw_aliases' => ['HOOVINAHADAGALI', 'HADAGALI', 'HOOVINAHADAGALI APMC'],
            ],
            [
                'name' => 'Kottur APMC',
                'name_kn' => 'ಕೊಟ್ಟೂರು ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_KTR',
                'district' => 'Vijayanagara',
                'market_type' => 'APMC',
                'lat' => 14.9300,
                'lon' => 76.2200,
                'address' => 'APMC Yard, Kottur, Vijayanagara District',
                'raw_aliases' => ['KOTTUR', 'KOTTURU', 'KOTTUR APMC'],
            ],

            // ==========================================
            // YADGIR (ಯಾದಗಿರಿ)
            // ==========================================
            [
                'name' => 'Yadgir APMC',
                'name_kn' => 'ಯಾದಗಿರಿ ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_YDG',
                'district' => 'Yadgir',
                'market_type' => 'APMC',
                'lat' => 16.7700,
                'lon' => 77.1300,
                'address' => 'APMC Yard, Yadgir',
                'raw_aliases' => ['YADGIR', 'YADAGIRI', 'YADGIR APMC'],
            ],

            // ==========================================
            // KODAGU (ಕೊಡಗು)
            // ==========================================
            [
                'name' => 'Madikeri Market',
                'name_kn' => 'ಮಡಿಕೇರಿ ಮಾರುಕಟ್ಟೆ',
                'code' => 'KA_MKT_MDK',
                'district' => 'Kodagu',
                'market_type' => 'APMC',
                'lat' => 12.4244,
                'lon' => 75.7382,
                'address' => 'APMC Market Yard, Madikeri, Kodagu',
                'raw_aliases' => ['MADIKERI', 'MERCARA', 'MADIKERI APMC'],
            ],
            [
                'name' => 'Somwarpet APMC',
                'name_kn' => 'ಸೋಮವಾರಪೇಟೆ ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_SWP',
                'district' => 'Kodagu',
                'market_type' => 'APMC',
                'lat' => 12.6000,
                'lon' => 75.8600,
                'address' => 'APMC Yard, Somwarpet, Kodagu District',
                'raw_aliases' => ['SOMWARPET', 'SOMAVARAPETE', 'SOMWARPET APMC'],
            ],
            [
                'name' => 'Gonikoppal APMC',
                'name_kn' => 'ಗೋಣಿಕೊಪ್ಪಲು ಎಪಿಎಂಸಿ',
                'code' => 'KA_APMC_GNK',
                'district' => 'Kodagu',
                'market_type' => 'APMC',
                'lat' => 12.1800,
                'lon' => 75.9300,
                'address' => 'APMC Yard, Gonikoppal, Kodagu District',
                'raw_aliases' => ['GONIKOPPAL', 'GONIKOPPA', 'GONIKOPPAL APMC'],
            ],

            // ==========================================
            // COMMODITY BOARDS & SPECIALIZED CENTRES
            // ==========================================
            [
                'name' => 'Madikeri (Coffee Board Centre)',
                'name_kn' => 'ಮಡಿಕೇರಿ (ಕಾಫಿ ಮಂಡಳಿ ಕೇಂದ್ರ)',
                'code' => 'CB_MDK',
                'district' => 'Kodagu',
                'market_type' => 'Private',
                'lat' => 12.4244,
                'lon' => 75.7382,
                'address' => 'Coffee Board Regional Office, Madikeri',
                'raw_aliases' => ['MADIKERI COFFEE BOARD', 'COFFEE BOARD MADIKERI'],
            ],
            [
                'name' => 'Chikkamagaluru (Coffee Board Centre)',
                'name_kn' => 'ಚಿಕ್ಕಮಗಳೂರು (ಕಾಫಿ ಮಂಡಳಿ ಕೇಂದ್ರ)',
                'code' => 'CB_CKM',
                'district' => 'Chikkamagaluru',
                'market_type' => 'Private',
                'lat' => 13.3161,
                'lon' => 75.7720,
                'address' => 'Coffee Board Office, Chikkamagaluru',
                'raw_aliases' => ['CHIKKAMAGALURU COFFEE BOARD', 'COFFEE BOARD CHIKKAMAGALURU'],
            ],
            [
                'name' => 'Hassan (Coffee Board Centre)',
                'name_kn' => 'ಹಾಸನ (ಕಾಫಿ ಮಂಡಳಿ ಕೇಂದ್ರ)',
                'code' => 'CB_HSN',
                'district' => 'Hassan',
                'market_type' => 'Private',
                'lat' => 13.0033,
                'lon' => 76.1004,
                'address' => 'Coffee Board Office, B.M. Road, Hassan',
                'raw_aliases' => ['HASSAN COFFEE BOARD', 'COFFEE BOARD HASSAN'],
            ],
            [
                'name' => 'Arsikere (CDB Centre)',
                'name_kn' => 'ಅರಸೀಕೆರೆ (ತೆಂಗು ಮಂಡಳಿ ಕೇಂದ್ರ)',
                'code' => 'CDB_ASK',
                'district' => 'Hassan',
                'market_type' => 'Private',
                'lat' => 13.3138,
                'lon' => 76.2570,
                'address' => 'Coconut Development Board Field Office, Arsikere',
                'raw_aliases' => ['ARSIKERE CDB', 'ARSIKERE COCONUT BOARD'],
            ],
            [
                'name' => 'Mandya (CDB Centre)',
                'name_kn' => 'ಮಂಡ್ಯ (ತೆಂಗು ಮಂಡಳಿ ಕೇಂದ್ರ)',
                'code' => 'CDB_MDY',
                'district' => 'Mandya',
                'market_type' => 'Private',
                'lat' => 12.5218,
                'lon' => 76.8951,
                'address' => 'Coconut Development Board Office, Mandya',
                'raw_aliases' => ['MANDYA CDB', 'MANDYA COCONUT BOARD'],
            ],
            [
                'name' => 'Tumakuru (CDB Centre)',
                'name_kn' => 'ತುಮಕೂರು (ತೆಂಗು ಮಂಡಳಿ ಕೇಂದ್ರ)',
                'code' => 'CDB_TMK',
                'district' => 'Tumakuru',
                'market_type' => 'Private',
                'lat' => 13.3409,
                'lon' => 77.1010,
                'address' => 'Coconut Development Board Office, Tumakuru',
                'raw_aliases' => ['TUMAKURU CDB', 'TUMAKURU COCONUT BOARD'],
            ],
            [
                'name' => 'Tiptur (CDB Centre)',
                'name_kn' => 'ತಿಪಟೂರು (ತೆಂಗು ಮಂಡಳಿ ಕೇಂದ್ರ)',
                'code' => 'CDB_TPT',
                'district' => 'Tumakuru',
                'market_type' => 'Private',
                'lat' => 13.2570,
                'lon' => 76.4780,
                'address' => 'Coconut Development Board Office, Tiptur',
                'raw_aliases' => ['TIPTUR CDB', 'TIPTUR COCONUT BOARD'],
            ],
        ];
    }
}
