<?php

namespace App\Support;

class KarnatakaMandiDirectory
{
    /**
     * Complete Standard Karnataka APMC and Board Market Directory (KRAMA Aligned).
     * Covers all APMC yards across all 31 Karnataka districts.
     *
     * @return array<int, array<string, mixed>>
     */
    public static function all(): array
    {
        return [
            // ==========================================
            // SHIVAMOGGA (ಶಿವಮೊಗ್ಗ)
            // ==========================================
            [
                'name' => 'Shivamogga',
                'name_kn' => 'ಶಿವಮೊಗ್ಗ',
                'code' => 'KA_APMC_SHI',
                'district' => 'Shivamogga',
                'market_type' => 'APMC',
                'lat' => 13.9310,
                'lon' => 75.5700,
                'address' => 'APMC Market Yard, B.H. Road, Shivamogga',
                'raw_aliases' => ['SHIVAMOGGA', 'SHIMOGA'],
            ],
            [
                'name' => 'Thirthahalli',
                'name_kn' => 'ತೀರ್ಥಹಳ್ಳಿ',
                'code' => 'KA_APMC_THI',
                'district' => 'Shivamogga',
                'market_type' => 'APMC',
                'lat' => 13.7000,
                'lon' => 75.2400,
                'address' => 'APMC Market Yard, Thirthahalli, Shivamogga District',
                'raw_aliases' => ['TIRTHAHALLI', 'THIRTHAHALLI'],
            ],
            [
                'name' => 'Sagara',
                'name_kn' => 'ಸಾಗರ',
                'code' => 'KA_APMC_SAG',
                'district' => 'Shivamogga',
                'market_type' => 'APMC',
                'lat' => 14.1670,
                'lon' => 75.0330,
                'address' => 'APMC Yard, Sagara, Shivamogga District',
                'raw_aliases' => ['SAGAR', 'SAGARA'],
            ],
            [
                'name' => 'Shikaripura',
                'name_kn' => 'ಶಿಕಾರಿಪುರ',
                'code' => 'KA_APMC_SKP',
                'district' => 'Shivamogga',
                'market_type' => 'APMC',
                'lat' => 14.2690,
                'lon' => 75.3530,
                'address' => 'APMC Yard, Shikaripura, Shivamogga District',
                'raw_aliases' => ['SHIKARIPUR', 'SHIKARIPURA'],
            ],
            [
                'name' => 'Bhadravathi',
                'name_kn' => 'ಭದ್ರಾವತಿ',
                'code' => 'KA_APMC_BDV',
                'district' => 'Shivamogga',
                'market_type' => 'APMC',
                'lat' => 13.8400,
                'lon' => 75.7000,
                'address' => 'APMC Yard, Bhadravathi, Shivamogga District',
                'raw_aliases' => ['BHADRAVATHI', 'BHADRAVATI'],
            ],
            [
                'name' => 'Soraba',
                'name_kn' => 'ಸೊರಬ',
                'code' => 'KA_APMC_SRB',
                'district' => 'Shivamogga',
                'market_type' => 'APMC',
                'lat' => 14.3800,
                'lon' => 75.1000,
                'address' => 'APMC Yard, Soraba, Shivamogga District',
                'raw_aliases' => ['SORABHA', 'SORABA'],
            ],
            [
                'name' => 'Hosanagar',
                'name_kn' => 'ಹೊಸನಗರ',
                'code' => 'KA_APMC_HSN_S',
                'district' => 'Shivamogga',
                'market_type' => 'APMC',
                'lat' => 13.9200,
                'lon' => 75.0700,
                'address' => 'APMC Yard, Hosanagar, Shivamogga District',
                'raw_aliases' => ['HOSANAGAR', 'HOSANAGARA'],
            ],

            // ==========================================
            // DAVANAGERE (ದಾವಣಗೆರೆ)
            // ==========================================
            [
                'name' => 'Davanagere',
                'name_kn' => 'ದಾವಣಗೆರೆ',
                'code' => 'KA_APMC_DVG',
                'district' => 'Davanagere',
                'market_type' => 'APMC',
                'lat' => 14.4644,
                'lon' => 75.9218,
                'address' => 'APMC Market Yard, Davanagere',
                'raw_aliases' => ['DAVANAGERE', 'DAVANGERE'],
            ],
            [
                'name' => 'Channagiri',
                'name_kn' => 'ಚನ್ನಗಿರಿ',
                'code' => 'KA_APMC_CNG',
                'district' => 'Davanagere',
                'market_type' => 'APMC',
                'lat' => 14.0270,
                'lon' => 75.9260,
                'address' => 'APMC Yard, Main Road, Channagiri',
                'raw_aliases' => ['CHANNAGIRI'],
            ],
            [
                'name' => 'Harihara',
                'name_kn' => 'ಹರಿಹರ',
                'code' => 'KA_APMC_HRH',
                'district' => 'Davanagere',
                'market_type' => 'APMC',
                'lat' => 14.5120,
                'lon' => 75.8050,
                'address' => 'APMC Yard, Harihara, Davanagere District',
                'raw_aliases' => ['HARIHARA', 'HARIHAR'],
            ],
            [
                'name' => 'Honnali',
                'name_kn' => 'ಹೊನ್ನಾಳಿ',
                'code' => 'KA_APMC_HNL',
                'district' => 'Davanagere',
                'market_type' => 'APMC',
                'lat' => 14.2440,
                'lon' => 75.6440,
                'address' => 'APMC Yard, Honnali, Davanagere District',
                'raw_aliases' => ['HONNALI'],
            ],
            [
                'name' => 'Jagalur',
                'name_kn' => 'ಜಗಳೂರು',
                'code' => 'KA_APMC_JGL',
                'district' => 'Davanagere',
                'market_type' => 'APMC',
                'lat' => 14.5200,
                'lon' => 76.3500,
                'address' => 'APMC Yard, Jagalur, Davanagere District',
                'raw_aliases' => ['JAGALUR'],
            ],
            [
                'name' => 'Nyamathi',
                'name_kn' => 'ನ್ಯಾಮತಿ',
                'code' => 'KA_APMC_NMT',
                'district' => 'Davanagere',
                'market_type' => 'APMC',
                'lat' => 14.1500,
                'lon' => 75.5800,
                'address' => 'APMC Yard, Nyamathi, Davanagere District',
                'raw_aliases' => ['NYAMATHI'],
            ],

            // ==========================================
            // UTTARA KANNADA (ಉತ್ತರ ಕನ್ನಡ)
            // ==========================================
            [
                'name' => 'Sirsi (TSS)',
                'name_kn' => 'ಶಿರಸಿ (ಟಿಎಸ್ಎಸ್)',
                'code' => 'KA_APMC_SRS',
                'district' => 'Uttara Kannada',
                'market_type' => 'APMC',
                'lat' => 14.6195,
                'lon' => 74.8354,
                'address' => 'TSS APMC Yard, Sirsi, Uttara Kannada',
                'raw_aliases' => ['SIRSI', 'SIRSI (TSS)', 'TSS SIRSI'],
            ],
            [
                'name' => 'Yellapur',
                'name_kn' => 'ಯಲ್ಲಾಪುರ',
                'code' => 'KA_APMC_YLP',
                'district' => 'Uttara Kannada',
                'market_type' => 'APMC',
                'lat' => 14.9640,
                'lon' => 74.7120,
                'address' => 'APMC Yard, Yellapur, Uttara Kannada',
                'raw_aliases' => ['YELLAPURA', 'YELLAPUR'],
            ],
            [
                'name' => 'Kumta',
                'name_kn' => 'ಕುಮಟಾ',
                'code' => 'KA_APMC_KMT',
                'district' => 'Uttara Kannada',
                'market_type' => 'APMC',
                'lat' => 14.4270,
                'lon' => 74.4080,
                'address' => 'APMC Yard, Kumta, Uttara Kannada',
                'raw_aliases' => ['KUMTA'],
            ],
            [
                'name' => 'Siddapur',
                'name_kn' => 'ಸಿದ್ಧಾಪುರ',
                'code' => 'KA_APMC_SDP',
                'district' => 'Uttara Kannada',
                'market_type' => 'APMC',
                'lat' => 14.3400,
                'lon' => 74.8900,
                'address' => 'APMC Yard, Siddapur, Uttara Kannada',
                'raw_aliases' => ['SIDDAPURA', 'SIDDAPUR'],
            ],
            [
                'name' => 'Mundgod',
                'name_kn' => 'ಮುಂಡಗೋಡ',
                'code' => 'KA_APMC_MDG_U',
                'district' => 'Uttara Kannada',
                'market_type' => 'APMC',
                'lat' => 14.9700,
                'lon' => 75.0300,
                'address' => 'APMC Yard, Mundgod, Uttara Kannada',
                'raw_aliases' => ['MUNDAGOD', 'MUNDGOD'],
            ],
            [
                'name' => 'Honnavar',
                'name_kn' => 'ಹೊನ್ನಾವರ',
                'code' => 'KA_APMC_HNV',
                'district' => 'Uttara Kannada',
                'market_type' => 'APMC',
                'lat' => 14.2800,
                'lon' => 74.4500,
                'address' => 'APMC Yard, Honnavar, Uttara Kannada',
                'raw_aliases' => ['HONNAVAR'],
            ],
            [
                'name' => 'Haliyal',
                'name_kn' => 'ಹಳಿಯಾಳ',
                'code' => 'KA_APMC_HLY_U',
                'district' => 'Uttara Kannada',
                'market_type' => 'APMC',
                'lat' => 15.3300,
                'lon' => 74.7600,
                'address' => 'APMC Yard, Haliyal, Uttara Kannada',
                'raw_aliases' => ['HALIYALA', 'HALIYAL'],
            ],
            [
                'name' => 'Karwar',
                'name_kn' => 'ಕಾರವಾರ',
                'code' => 'KA_APMC_KRW',
                'district' => 'Uttara Kannada',
                'market_type' => 'APMC',
                'lat' => 14.8100,
                'lon' => 74.1300,
                'address' => 'APMC Yard, Karwar, Uttara Kannada',
                'raw_aliases' => ['KARWAR'],
            ],
            [
                'name' => 'Bhatkal',
                'name_kn' => 'ಭಟ್ಕಳ',
                'code' => 'KA_APMC_BTK',
                'district' => 'Uttara Kannada',
                'market_type' => 'APMC',
                'lat' => 13.9700,
                'lon' => 74.5500,
                'address' => 'APMC Yard, Bhatkal, Uttara Kannada',
                'raw_aliases' => ['BHATKAL'],
            ],
            [
                'name' => 'Ankola',
                'name_kn' => 'ಅಂಕೋಲಾ',
                'code' => 'KA_APMC_ANK',
                'district' => 'Uttara Kannada',
                'market_type' => 'APMC',
                'lat' => 14.6600,
                'lon' => 74.3000,
                'address' => 'APMC Yard, Ankola, Uttara Kannada',
                'raw_aliases' => ['ANKOLA'],
            ],

            // ==========================================
            // DAKSHINA KANNADA (ದಕ್ಷಿಣ ಕನ್ನಡ)
            // ==========================================
            [
                'name' => 'Mangaluru (Baikampady)',
                'name_kn' => 'ಮಂಗಳೂರು (ಬೈಕಂಪಾಡಿ)',
                'code' => 'KA_APMC_MNG',
                'district' => 'Dakshina Kannada',
                'market_type' => 'APMC',
                'lat' => 12.9467,
                'lon' => 74.8122,
                'address' => 'APMC Yard, Baikampady, Mangaluru',
                'raw_aliases' => ['MANGALURU', 'MANGALORE'],
            ],
            [
                'name' => 'Bantwal',
                'name_kn' => 'ಬಂಟ್ವಾಳ',
                'code' => 'KA_APMC_BNT',
                'district' => 'Dakshina Kannada',
                'market_type' => 'APMC',
                'lat' => 12.8940,
                'lon' => 75.0330,
                'address' => 'APMC Yard, B.C. Road, Bantwal',
                'raw_aliases' => ['BANTWALA', 'BANTWAL'],
            ],
            [
                'name' => 'Puttur',
                'name_kn' => 'ಪುತ್ತೂರು',
                'code' => 'KA_APMC_PTR',
                'district' => 'Dakshina Kannada',
                'market_type' => 'APMC',
                'lat' => 12.7667,
                'lon' => 75.2000,
                'address' => 'APMC Yard, Puttur, Dakshina Kannada',
                'raw_aliases' => ['PUTTUR'],
            ],
            [
                'name' => 'Sullia',
                'name_kn' => 'ಸುಳ್ಯ',
                'code' => 'KA_APMC_SLA',
                'district' => 'Dakshina Kannada',
                'market_type' => 'APMC',
                'lat' => 12.5600,
                'lon' => 75.3900,
                'address' => 'APMC Yard, Sullia, Dakshina Kannada',
                'raw_aliases' => ['SULYA', 'SULLIA'],
            ],
            [
                'name' => 'Belthangadi',
                'name_kn' => 'ಬೆಳ್ತಂಗಡಿ',
                'code' => 'KA_APMC_BTG',
                'district' => 'Dakshina Kannada',
                'market_type' => 'APMC',
                'lat' => 13.0000,
                'lon' => 75.2600,
                'address' => 'APMC Yard, Belthangadi, Dakshina Kannada',
                'raw_aliases' => ['BELTHANGADI', 'BELTHANGADY'],
            ],

            // ==========================================
            // UDUPI (ಉಡುಪಿ)
            // ==========================================
            [
                'name' => 'Udupi',
                'name_kn' => 'ಉಡುಪಿ',
                'code' => 'KA_APMC_UDP',
                'district' => 'Udupi',
                'market_type' => 'APMC',
                'lat' => 13.3420,
                'lon' => 74.7450,
                'address' => 'APMC Market, Adi Udupi',
                'raw_aliases' => ['UDIPI', 'UDUPI'],
            ],
            [
                'name' => 'Kundapura',
                'name_kn' => 'ಕುಂದಾಪುರ',
                'code' => 'KA_APMC_KND',
                'district' => 'Udupi',
                'market_type' => 'APMC',
                'lat' => 13.6280,
                'lon' => 74.6950,
                'address' => 'APMC Yard, Kundapura, Udupi District',
                'raw_aliases' => ['KUNDAPUR', 'KUNDAPURA'],
            ],
            [
                'name' => 'Karkala',
                'name_kn' => 'ಕಾರ್ಕಳ',
                'code' => 'KA_APMC_KRK',
                'district' => 'Udupi',
                'market_type' => 'APMC',
                'lat' => 13.2100,
                'lon' => 74.9900,
                'address' => 'APMC Yard, Karkala, Udupi District',
                'raw_aliases' => ['KARKALA'],
            ],

            // ==========================================
            // CHIKKAMAGALURU (ಚಿಕ್ಕಮಗಳೂರು)
            // ==========================================
            [
                'name' => 'Chikkamagaluru',
                'name_kn' => 'ಚಿಕ್ಕಮಗಳೂರು',
                'code' => 'KA_APMC_CKM',
                'district' => 'Chikkamagaluru',
                'market_type' => 'APMC',
                'lat' => 13.3161,
                'lon' => 75.7720,
                'address' => 'APMC Yard, Chikkamagaluru',
                'raw_aliases' => ['CHIKKAMAGALURU', 'CHIKMAGALUR'],
            ],
            [
                'name' => 'Kadur',
                'name_kn' => 'ಕಡೂರು',
                'code' => 'KA_APMC_KDR',
                'district' => 'Chikkamagaluru',
                'market_type' => 'APMC',
                'lat' => 13.5530,
                'lon' => 76.0120,
                'address' => 'APMC Yard, Kadur, Chikkamagaluru District',
                'raw_aliases' => ['KADUR'],
            ],
            [
                'name' => 'Tarikere',
                'name_kn' => 'ತರೀಕೆರೆ',
                'code' => 'KA_APMC_TRK',
                'district' => 'Chikkamagaluru',
                'market_type' => 'APMC',
                'lat' => 13.7130,
                'lon' => 75.8150,
                'address' => 'APMC Yard, Tarikere, Chikkamagaluru District',
                'raw_aliases' => ['TARIKERE'],
            ],
            [
                'name' => 'Mudigere',
                'name_kn' => 'ಮೂಡಿಗೆರೆ',
                'code' => 'KA_APMC_MDG',
                'district' => 'Chikkamagaluru',
                'market_type' => 'APMC',
                'lat' => 13.1360,
                'lon' => 75.6400,
                'address' => 'APMC Yard, Mudigere, Chikkamagaluru District',
                'raw_aliases' => ['MUDIGERE'],
            ],
            [
                'name' => 'Koppa',
                'name_kn' => 'ಕೊಪ್ಪ',
                'code' => 'KA_APMC_KPA',
                'district' => 'Chikkamagaluru',
                'market_type' => 'APMC',
                'lat' => 13.5300,
                'lon' => 75.3600,
                'address' => 'APMC Yard, Koppa, Chikkamagaluru District',
                'raw_aliases' => ['KOPPA'],
            ],

            // ==========================================
            // HASSAN (ಹಾಸನ)
            // ==========================================
            [
                'name' => 'Hassan',
                'name_kn' => 'ಹಾಸನ',
                'code' => 'KA_APMC_HSN',
                'district' => 'Hassan',
                'market_type' => 'APMC',
                'lat' => 13.0033,
                'lon' => 76.1004,
                'address' => 'APMC Yard, B.M. Road, Hassan',
                'raw_aliases' => ['HASSAN'],
            ],
            [
                'name' => 'Arsikere',
                'name_kn' => 'ಅರಸೀಕೆರೆ',
                'code' => 'KA_APMC_ASK',
                'district' => 'Hassan',
                'market_type' => 'APMC',
                'lat' => 13.3138,
                'lon' => 76.2570,
                'address' => 'APMC Yard, Arsikere, Hassan District',
                'raw_aliases' => ['ARSIKERE', 'ARASIKERE'],
            ],
            [
                'name' => 'Channarayapatna',
                'name_kn' => 'ಚನ್ನರಾಯಪಟ್ಟಣ',
                'code' => 'KA_APMC_CRP',
                'district' => 'Hassan',
                'market_type' => 'APMC',
                'lat' => 12.9050,
                'lon' => 76.3880,
                'address' => 'APMC Yard, Channarayapatna, Hassan District',
                'raw_aliases' => ['C.R.PATNA', 'CHANNARAYAPATNA', 'C.R.PATNA APMC'],
            ],
            [
                'name' => 'Sakleshpur',
                'name_kn' => 'ಸಕಲೇಶಪುರ',
                'code' => 'KA_APMC_SKL',
                'district' => 'Hassan',
                'market_type' => 'APMC',
                'lat' => 12.9430,
                'lon' => 75.7870,
                'address' => 'APMC Yard, Sakleshpur, Hassan District',
                'raw_aliases' => ['SAKLESHPUR', 'SAKLESHPURA'],
            ],
            [
                'name' => 'Belur',
                'name_kn' => 'ಬೇಲೂರು',
                'code' => 'KA_APMC_BLR_H',
                'district' => 'Hassan',
                'market_type' => 'APMC',
                'lat' => 13.1600,
                'lon' => 75.8600,
                'address' => 'APMC Yard, Belur, Hassan District',
                'raw_aliases' => ['BELUR'],
            ],
            [
                'name' => 'Arakalgud',
                'name_kn' => 'ಅರಕಲಗೂಡು',
                'code' => 'KA_APMC_AKG',
                'district' => 'Hassan',
                'market_type' => 'APMC',
                'lat' => 12.7700,
                'lon' => 76.0600,
                'address' => 'APMC Yard, Arakalgud, Hassan District',
                'raw_aliases' => ['ARAKALGUD', 'ARAKALAGUDU'],
            ],
            [
                'name' => 'Holenarasipura',
                'name_kn' => 'ಹೊಳೆನರಸೀಪುರ',
                'code' => 'KA_APMC_HNP',
                'district' => 'Hassan',
                'market_type' => 'APMC',
                'lat' => 12.7900,
                'lon' => 76.2400,
                'address' => 'APMC Yard, Holenarasipura, Hassan District',
                'raw_aliases' => ['HOLENARASIPUR', 'HOLENARASIPURA'],
            ],

            // ==========================================
            // TUMAKURU (ತುಮಕೂರು)
            // ==========================================
            [
                'name' => 'Tumakuru',
                'name_kn' => 'ತುಮಕೂರು',
                'code' => 'KA_APMC_TMK',
                'district' => 'Tumakuru',
                'market_type' => 'APMC',
                'lat' => 13.3409,
                'lon' => 77.1010,
                'address' => 'APMC Yard, Batawadi, Tumakuru',
                'raw_aliases' => ['TUMAKURU', 'TUMKUR'],
            ],
            [
                'name' => 'Tiptur',
                'name_kn' => 'ತಿಪಟೂರು (ಕೊಬ್ಬರಿ ಮಾರುಕಟ್ಟೆ)',
                'code' => 'KA_APMC_TPT',
                'district' => 'Tumakuru',
                'market_type' => 'APMC',
                'lat' => 13.2570,
                'lon' => 76.4780,
                'address' => 'APMC Yard, Tiptur (Copra Capital)',
                'raw_aliases' => ['TIPTUR'],
            ],
            [
                'name' => 'Sira',
                'name_kn' => 'ಶಿರಾ',
                'code' => 'KA_APMC_SRA',
                'district' => 'Tumakuru',
                'market_type' => 'APMC',
                'lat' => 13.7400,
                'lon' => 76.9000,
                'address' => 'APMC Yard, Sira, Tumakuru District',
                'raw_aliases' => ['SIRA'],
            ],
            [
                'name' => 'Gubbi',
                'name_kn' => 'ಗುಬ್ಬಿ',
                'code' => 'KA_APMC_GBI',
                'district' => 'Tumakuru',
                'market_type' => 'APMC',
                'lat' => 13.3100,
                'lon' => 76.9400,
                'address' => 'APMC Yard, Gubbi, Tumakuru District',
                'raw_aliases' => ['GUBBI'],
            ],
            [
                'name' => 'Turuvekere',
                'name_kn' => 'ತುರುವೇಕೆರೆ',
                'code' => 'KA_APMC_TRV',
                'district' => 'Tumakuru',
                'market_type' => 'APMC',
                'lat' => 13.1600,
                'lon' => 76.6700,
                'address' => 'APMC Yard, Turuvekere, Tumakuru District',
                'raw_aliases' => ['TURUVEKERE'],
            ],
            [
                'name' => 'Huliyar',
                'name_kn' => 'ಹುಳಿಯಾರು',
                'code' => 'KA_APMC_HLY_T',
                'district' => 'Tumakuru',
                'market_type' => 'APMC',
                'lat' => 13.5800,
                'lon' => 76.5400,
                'address' => 'APMC Yard, Huliyar, C.N.Halli Taluk',
                'raw_aliases' => ['HULIYAR'],
            ],

            // ==========================================
            // CHITRADURGA (ಚಿತ್ರದುರ್ಗ)
            // ==========================================
            [
                'name' => 'Chitradurga',
                'name_kn' => 'ಚಿತ್ರದುರ್ಗ',
                'code' => 'KA_APMC_CTA',
                'district' => 'Chitradurga',
                'market_type' => 'APMC',
                'lat' => 14.2251,
                'lon' => 76.4020,
                'address' => 'APMC Yard, Chitradurga',
                'raw_aliases' => ['CHITRADURGA'],
            ],
            [
                'name' => 'Challakere',
                'name_kn' => 'ಚಳ್ಳಕೆರೆ (ಎಣ್ಣೆಬೀಜ ಮಾರುಕಟ್ಟೆ)',
                'code' => 'KA_APMC_CLK',
                'district' => 'Chitradurga',
                'market_type' => 'APMC',
                'lat' => 14.3130,
                'lon' => 76.6510,
                'address' => 'APMC Yard, Challakere (Oil Seeds City)',
                'raw_aliases' => ['CHALLAKERE'],
            ],
            [
                'name' => 'Hiriyur',
                'name_kn' => 'ಹಿರಿಯೂರು',
                'code' => 'KA_APMC_HRY',
                'district' => 'Chitradurga',
                'market_type' => 'APMC',
                'lat' => 13.9450,
                'lon' => 76.6180,
                'address' => 'APMC Yard, Hiriyur, Chitradurga District',
                'raw_aliases' => ['HIRIYUR'],
            ],
            [
                'name' => 'Hosadurga',
                'name_kn' => 'ಹೊಸದುರ್ಗ',
                'code' => 'KA_APMC_HSD',
                'district' => 'Chitradurga',
                'market_type' => 'APMC',
                'lat' => 13.7990,
                'lon' => 76.2850,
                'address' => 'APMC Yard, Hosadurga, Chitradurga District',
                'raw_aliases' => ['HOSADURGA'],
            ],
            [
                'name' => 'Holalkere',
                'name_kn' => 'ಹೊಳಲ್ಕೆರೆ',
                'code' => 'KA_APMC_HLK',
                'district' => 'Chitradurga',
                'market_type' => 'APMC',
                'lat' => 14.0320,
                'lon' => 76.1830,
                'address' => 'APMC Yard, Holalkere, Chitradurga District',
                'raw_aliases' => ['HOLALKERE'],
            ],

            // ==========================================
            // KOLAR (ಕೋಲಾರ)
            // ==========================================
            [
                'name' => 'Kolar (Tomato Market)',
                'name_kn' => 'ಕೋಲಾರ (ಟೊಮೆಟೊ ಮಾರುಕಟ್ಟೆ)',
                'code' => 'KA_APMC_KLR',
                'district' => 'Kolar',
                'market_type' => 'APMC',
                'lat' => 13.1380,
                'lon' => 78.1350,
                'address' => 'APMC Yard, Kolar (Asia Second Largest Tomato Mandi)',
                'raw_aliases' => ['KOLAR'],
            ],
            [
                'name' => 'Bangarpet',
                'name_kn' => 'ಬಂಗಾರಪೇಟೆ',
                'code' => 'KA_APMC_BPT',
                'district' => 'Kolar',
                'market_type' => 'APMC',
                'lat' => 12.9800,
                'lon' => 78.2000,
                'address' => 'APMC Yard, Bangarpet, Kolar District',
                'raw_aliases' => ['BANGARPET', 'BANGARAPETE'],
            ],
            [
                'name' => 'Malur',
                'name_kn' => 'ಮಾಲೂರು',
                'code' => 'KA_APMC_MLR',
                'district' => 'Kolar',
                'market_type' => 'APMC',
                'lat' => 13.0000,
                'lon' => 77.9400,
                'address' => 'APMC Yard, Malur, Kolar District',
                'raw_aliases' => ['MALUR'],
            ],
            [
                'name' => 'Mulbagal',
                'name_kn' => 'ಮುಳಬಾಗಿಲು',
                'code' => 'KA_APMC_MLB',
                'district' => 'Kolar',
                'market_type' => 'APMC',
                'lat' => 13.1600,
                'lon' => 78.3900,
                'address' => 'APMC Yard, Mulbagal, Kolar District',
                'raw_aliases' => ['MULBAGAL', 'MULABAGILU'],
            ],
            [
                'name' => 'Srinivaspur',
                'name_kn' => 'ಶ್ರೀನಿವಾಸಪುರ (ಮಾವು ಮಾರುಕಟ್ಟೆ)',
                'code' => 'KA_APMC_SVP',
                'district' => 'Kolar',
                'market_type' => 'APMC',
                'lat' => 13.3400,
                'lon' => 78.2100,
                'address' => 'APMC Yard, Srinivaspur (Mango Capital)',
                'raw_aliases' => ['SRINIVASPUR', 'SRINIVASAPURA'],
            ],

            // ==========================================
            // CHIKKABALLAPURA (ಚಿಕ್ಕಬಳ್ಳಾಪುರ)
            // ==========================================
            [
                'name' => 'Chikkaballapura',
                'name_kn' => 'ಚಿಕ್ಕಬಳ್ಳಾಪುರ',
                'code' => 'KA_APMC_CKB',
                'district' => 'Chikkaballapura',
                'market_type' => 'APMC',
                'lat' => 13.4355,
                'lon' => 77.7315,
                'address' => 'APMC Yard, Chikkaballapura',
                'raw_aliases' => ['CHICKBALLAPUR', 'CHIKKABALLAPUR'],
            ],
            [
                'name' => 'Chintamani',
                'name_kn' => 'ಚಿಂತಾಮಣಿ',
                'code' => 'KA_APMC_CTM',
                'district' => 'Chikkaballapura',
                'market_type' => 'APMC',
                'lat' => 13.4000,
                'lon' => 78.0600,
                'address' => 'APMC Yard, Chintamani, Chikkaballapura District',
                'raw_aliases' => ['CHINTAMANI', 'CHINTHAMANI'],
            ],
            [
                'name' => 'Gowribidnur',
                'name_kn' => 'ಗೌರಿಬಿದನೂರು',
                'code' => 'KA_APMC_GBN',
                'district' => 'Chikkaballapura',
                'market_type' => 'APMC',
                'lat' => 13.6100,
                'lon' => 77.5200,
                'address' => 'APMC Yard, Gowribidnur, Chikkaballapura District',
                'raw_aliases' => ['GOWRIBIDNUR', 'GAURIBIDANUR'],
            ],
            [
                'name' => 'Bagepalli',
                'name_kn' => 'ಬಾಗೇಪಲ್ಲಿ',
                'code' => 'KA_APMC_BGP',
                'district' => 'Chikkaballapura',
                'market_type' => 'APMC',
                'lat' => 13.7800,
                'lon' => 77.7900,
                'address' => 'APMC Yard, Bagepalli, Chikkaballapura District',
                'raw_aliases' => ['BAGEPALLI'],
            ],
            [
                'name' => 'Sidlaghatta',
                'name_kn' => 'ಶಿಡ್ಲಘಟ್ಟ',
                'code' => 'KA_APMC_SDG',
                'district' => 'Chikkaballapura',
                'market_type' => 'APMC',
                'lat' => 13.3900,
                'lon' => 77.8600,
                'address' => 'APMC Yard, Sidlaghatta, Chikkaballapura District',
                'raw_aliases' => ['SIDLAGHATTA', 'SHIDLAGHATTA'],
            ],

            // ==========================================
            // BENGALURU URBAN & RURAL (ಬೆಂಗಳೂರು)
            // ==========================================
            [
                'name' => 'Yeshwanthpur',
                'name_kn' => 'ಯಶವಂತಪುರ',
                'code' => 'KA_APMC_YPR',
                'district' => 'Bengaluru Urban',
                'market_type' => 'APMC',
                'lat' => 13.0238,
                'lon' => 77.5458,
                'address' => 'APMC Yard, Yeshwanthpur, Bengaluru',
                'raw_aliases' => ['YESHWANTHPUR'],
            ],
            [
                'name' => 'Binny Mill (F&V)',
                'name_kn' => 'ಬಿನ್ನಿ ಮಿಲ್ (ಹಣ್ಣು ಮತ್ತು ತರಕಾರಿ)',
                'code' => 'KA_APMC_BNM',
                'district' => 'Bengaluru Urban',
                'market_type' => 'Specialized Market',
                'lat' => 12.9667,
                'lon' => 77.5667,
                'address' => 'Binny Mill Market, Cottonpet, Bengaluru',
                'raw_aliases' => ['BINNY MILL (F&V)', 'BINNY MILL', 'BINNY MILLS'],
            ],
            [
                'name' => 'Bengaluru',
                'name_kn' => 'ಬೆಂಗಳೂರು',
                'code' => 'KA_APMC_BLR',
                'district' => 'Bengaluru Urban',
                'market_type' => 'APMC',
                'lat' => 12.9716,
                'lon' => 77.5946,
                'address' => 'APMC Market Yard, Bengaluru Urban',
                'raw_aliases' => ['BENGALURU', 'BANGALORE'],
            ],
            [
                'name' => 'Doddaballapur',
                'name_kn' => 'ದೊಡ್ಡಬಳ್ಳಾಪುರ',
                'code' => 'KA_APMC_DBP',
                'district' => 'Bengaluru Rural',
                'market_type' => 'APMC',
                'lat' => 13.2929,
                'lon' => 77.5428,
                'address' => 'APMC Yard, Doddaballapur, Bengaluru Rural',
                'raw_aliases' => ['DODDABALLAPUR', 'DODDABALLAPURA'],
            ],
            [
                'name' => 'Hoskote',
                'name_kn' => 'ಹೊಸಕೋಟೆ',
                'code' => 'KA_APMC_HSK',
                'district' => 'Bengaluru Rural',
                'market_type' => 'APMC',
                'lat' => 13.0700,
                'lon' => 77.8000,
                'address' => 'APMC Yard, Hoskote, Bengaluru Rural',
                'raw_aliases' => ['HOSKOTE', 'HOSAKOTE'],
            ],

            // ==========================================
            // MANDYA (ಮಂಡ್ಯ)
            // ==========================================
            [
                'name' => 'Mandya',
                'name_kn' => 'ಮಂಡ್ಯ',
                'code' => 'KA_APMC_MDY',
                'district' => 'Mandya',
                'market_type' => 'APMC',
                'lat' => 12.5218,
                'lon' => 76.8951,
                'address' => 'APMC Yard, Mandya',
                'raw_aliases' => ['MANDYA'],
            ],
            [
                'name' => 'Maddur',
                'name_kn' => 'ಮದ್ದೂರು (ಎಳನೀರು ಮಾರುಕಟ್ಟೆ)',
                'code' => 'KA_APMC_MDR',
                'district' => 'Mandya',
                'market_type' => 'APMC',
                'lat' => 12.5840,
                'lon' => 77.0450,
                'address' => 'APMC Yard, Maddur (Tender Coconut Hub)',
                'raw_aliases' => ['MADDUR'],
            ],
            [
                'name' => 'Malavalli',
                'name_kn' => 'ಮಳವಳ್ಳಿ',
                'code' => 'KA_APMC_MLV',
                'district' => 'Mandya',
                'market_type' => 'APMC',
                'lat' => 12.3800,
                'lon' => 77.0600,
                'address' => 'APMC Yard, Malavalli, Mandya District',
                'raw_aliases' => ['MALAVALLI'],
            ],
            [
                'name' => 'Pandavapura',
                'name_kn' => 'ಪಾಂಡವಪುರ',
                'code' => 'KA_APMC_PDP',
                'district' => 'Mandya',
                'market_type' => 'APMC',
                'lat' => 12.5000,
                'lon' => 76.6700,
                'address' => 'APMC Yard, Pandavapura, Mandya District',
                'raw_aliases' => ['PANDAVAPURA'],
            ],
            [
                'name' => 'Krishnarajapete',
                'name_kn' => 'ಕೃಷ್ಣರಾಜಪೇಟೆ',
                'code' => 'KA_APMC_KRP',
                'district' => 'Mandya',
                'market_type' => 'APMC',
                'lat' => 12.6600,
                'lon' => 76.4900,
                'address' => 'APMC Yard, K.R.Pet, Mandya District',
                'raw_aliases' => ['K.R.PET', 'KRISHNARAJAPET', 'K.R.PET APMC'],
            ],
            [
                'name' => 'Nagamangala',
                'name_kn' => 'ನಾಗಮಂಗಲ',
                'code' => 'KA_APMC_NGM',
                'district' => 'Mandya',
                'market_type' => 'APMC',
                'lat' => 12.8200,
                'lon' => 76.7600,
                'address' => 'APMC Yard, Nagamangala, Mandya District',
                'raw_aliases' => ['NAGAMANGALA'],
            ],
            [
                'name' => 'Srirangapatna',
                'name_kn' => 'ಶ್ರೀರಂಗಪಟ್ಟಣ',
                'code' => 'KA_APMC_SRP',
                'district' => 'Mandya',
                'market_type' => 'APMC',
                'lat' => 12.4200,
                'lon' => 76.6900,
                'address' => 'APMC Yard, Srirangapatna, Mandya District',
                'raw_aliases' => ['SRIRANGAPATNA', 'SRIRANGAPATTANA'],
            ],

            // ==========================================
            // MYSURU (ಮೈಸೂರು)
            // ==========================================
            [
                'name' => 'Mysuru (Bandipalya)',
                'name_kn' => 'ಮೈಸೂರು (ಬಂಡಿಪಾಳ್ಯ)',
                'code' => 'KA_APMC_MYS',
                'district' => 'Mysuru',
                'market_type' => 'APMC',
                'lat' => 12.2740,
                'lon' => 76.6690,
                'address' => 'APMC Bandipalya Yard, Mysuru',
                'raw_aliases' => ['MYSURU', 'MYSORE', 'BANDIPALYA'],
            ],
            [
                'name' => 'Nanjangud',
                'name_kn' => 'ನಂಜನಗೂಡು',
                'code' => 'KA_APMC_NJG',
                'district' => 'Mysuru',
                'market_type' => 'APMC',
                'lat' => 12.1190,
                'lon' => 76.6830,
                'address' => 'APMC Yard, Nanjangud, Mysuru District',
                'raw_aliases' => ['NANJANGUD', 'NANJANAGUDU'],
            ],
            [
                'name' => 'Hunsur',
                'name_kn' => 'ಹುಣಸೂರು',
                'code' => 'KA_APMC_HNS',
                'district' => 'Mysuru',
                'market_type' => 'APMC',
                'lat' => 12.3100,
                'lon' => 76.2900,
                'address' => 'APMC Yard, Hunsur, Mysuru District',
                'raw_aliases' => ['HUNSUR', 'HUNASURU'],
            ],
            [
                'name' => 'T. Narasipura',
                'name_kn' => 'ಟಿ. ನರಸೀಪುರ',
                'code' => 'KA_APMC_TNP',
                'district' => 'Mysuru',
                'market_type' => 'APMC',
                'lat' => 12.2100,
                'lon' => 76.9000,
                'address' => 'APMC Yard, T.Narsipur, Mysuru District',
                'raw_aliases' => ['T.NARSIPUR', 'T.NARASIPURA', 'T.NARSIPUR APMC'],
            ],
            [
                'name' => 'Krishnarajanagara',
                'name_kn' => 'ಕೆ.ಆರ್.ನಗರ',
                'code' => 'KA_APMC_KRN',
                'district' => 'Mysuru',
                'market_type' => 'APMC',
                'lat' => 12.5800,
                'lon' => 76.3800,
                'address' => 'APMC Yard, K.R.Nagar, Mysuru District',
                'raw_aliases' => ['K.R.NAGAR', 'KRISHNARAJANAGAR', 'K.R.NAGAR APMC'],
            ],
            [
                'name' => 'Periyapatna',
                'name_kn' => 'ಪಿರಿಯಾಪಟ್ಟಣ',
                'code' => 'KA_APMC_PPT',
                'district' => 'Mysuru',
                'market_type' => 'APMC',
                'lat' => 12.3400,
                'lon' => 76.1000,
                'address' => 'APMC Yard, Periyapatna, Mysuru District',
                'raw_aliases' => ['PERIYAPATNA', 'PIRIYAPATNA'],
            ],

            // ==========================================
            // CHAMARAJANAGAR (ಚಾಮರಾಜನಗರ)
            // ==========================================
            [
                'name' => 'Chamarajanagar',
                'name_kn' => 'ಚಾಮರಾಜನಗರ',
                'code' => 'KA_APMC_CRN',
                'district' => 'Chamarajanagar',
                'market_type' => 'APMC',
                'lat' => 11.9261,
                'lon' => 76.9437,
                'address' => 'APMC Yard, Chamarajanagar',
                'raw_aliases' => ['C.R.NAGAR', 'CHAMARAJANAGAR', 'C.R.NAGAR APMC'],
            ],
            [
                'name' => 'Kollegal',
                'name_kn' => 'ಕೊಳ್ಳೇಗಾಲ',
                'code' => 'KA_APMC_KLG',
                'district' => 'Chamarajanagar',
                'market_type' => 'APMC',
                'lat' => 12.1550,
                'lon' => 77.1120,
                'address' => 'APMC Yard, Kollegal, Chamarajanagar District',
                'raw_aliases' => ['KOLLEGAL', 'KOLLEGALA'],
            ],
            [
                'name' => 'Gundlupet',
                'name_kn' => 'ಗುಂಡ್ಲುಪೇಟೆ',
                'code' => 'KA_APMC_GLP',
                'district' => 'Chamarajanagar',
                'market_type' => 'APMC',
                'lat' => 11.8100,
                'lon' => 76.6900,
                'address' => 'APMC Yard, Gundlupet, Chamarajanagar District',
                'raw_aliases' => ['GUNDLUPET', 'GUNDLUPETE'],
            ],
            [
                'name' => 'Hanur',
                'name_kn' => 'ಹನೂರು',
                'code' => 'KA_APMC_HNR',
                'district' => 'Chamarajanagar',
                'market_type' => 'APMC',
                'lat' => 12.0900,
                'lon' => 77.3000,
                'address' => 'APMC Yard, Hanur, Chamarajanagar District',
                'raw_aliases' => ['HANUR'],
            ],
            [
                'name' => 'Santhemarahalli',
                'name_kn' => 'ಸಂತೆಮರಹಳ್ಳಿ',
                'code' => 'KA_APMC_SMH',
                'district' => 'Chamarajanagar',
                'market_type' => 'APMC',
                'lat' => 11.9800,
                'lon' => 76.9900,
                'address' => 'APMC Yard, Santhemarahalli, Chamarajanagar District',
                'raw_aliases' => ['SANTHESARGUR', 'SANTHEMARAHALLI'],
            ],

            // ==========================================
            // RAMANAGARA (ರಾಮನಗರ)
            // ==========================================
            [
                'name' => 'Ramanagara Silk Cocoon Market',
                'name_kn' => 'ರಾಮನಗರ ರೇಷ್ಮೆ ಗೂಡು ಮಾರುಕಟ್ಟೆ',
                'code' => 'KA_MKT_RAM',
                'district' => 'Ramanagara',
                'market_type' => 'Specialized Market',
                'lat' => 12.7214,
                'lon' => 77.2807,
                'address' => 'Government Silk Cocoon Market, Ramanagara',
                'raw_aliases' => ['RAMANAGARA SILK', 'RAMANAGARA SILK COCOON'],
            ],
            [
                'name' => 'Ramanagara',
                'name_kn' => 'ರಾಮನಗರ',
                'code' => 'KA_APMC_RMN',
                'district' => 'Ramanagara',
                'market_type' => 'APMC',
                'lat' => 12.7214,
                'lon' => 77.2807,
                'address' => 'APMC Yard, Ramanagara',
                'raw_aliases' => ['RAMANAGARA', 'RAMANAGARAM'],
            ],
            [
                'name' => 'Channapatna',
                'name_kn' => 'ಚನ್ನಪಟ್ಟಣ',
                'code' => 'KA_APMC_CPT',
                'district' => 'Ramanagara',
                'market_type' => 'APMC',
                'lat' => 12.6500,
                'lon' => 77.2000,
                'address' => 'APMC Yard, Channapatna, Ramanagara District',
                'raw_aliases' => ['CHANNAPATNA', 'CHANNAPATTANA'],
            ],
            [
                'name' => 'Kanakapura',
                'name_kn' => 'ಕನಕಪುರ',
                'code' => 'KA_APMC_KKP',
                'district' => 'Ramanagara',
                'market_type' => 'APMC',
                'lat' => 12.5500,
                'lon' => 77.4100,
                'address' => 'APMC Yard, Kanakapura, Ramanagara District',
                'raw_aliases' => ['KANAKAPURA'],
            ],

            // ==========================================
            // DHARWAD (ಧಾರವಾಡ)
            // ==========================================
            [
                'name' => 'Hubballi (Amaragol)',
                'name_kn' => 'ಹುಬ್ಬಳ್ಳಿ (ಅಮರಗೋಳ)',
                'code' => 'KA_APMC_HBL',
                'district' => 'Dharwad',
                'market_type' => 'APMC',
                'lat' => 15.3950,
                'lon' => 75.0930,
                'address' => 'Amaragol APMC Yard, Hubballi',
                'raw_aliases' => ['HUBBALLI', 'HUBLI', 'AMARAGOL'],
            ],
            [
                'name' => 'Dharwad',
                'name_kn' => 'ಧಾರವಾಡ',
                'code' => 'KA_APMC_DWR',
                'district' => 'Dharwad',
                'market_type' => 'APMC',
                'lat' => 15.4589,
                'lon' => 75.0078,
                'address' => 'APMC Yard, Dharwad',
                'raw_aliases' => ['DHARWAR', 'DHARWAD'],
            ],
            [
                'name' => 'Annigeri',
                'name_kn' => 'ಅಣ್ಣಿಗೇರಿ',
                'code' => 'KA_APMC_ANG',
                'district' => 'Dharwad',
                'market_type' => 'APMC',
                'lat' => 15.4300,
                'lon' => 75.4300,
                'address' => 'APMC Yard, Annigeri, Dharwad District',
                'raw_aliases' => ['ANNIGERI'],
            ],
            [
                'name' => 'Kundgol',
                'name_kn' => 'ಕುಂದಗೋಳ',
                'code' => 'KA_APMC_KDG',
                'district' => 'Dharwad',
                'market_type' => 'APMC',
                'lat' => 15.2500,
                'lon' => 75.2500,
                'address' => 'APMC Yard, Kundgol, Dharwad District',
                'raw_aliases' => ['KUNDGOL', 'KUNDAGOL'],
            ],
            [
                'name' => 'Kalghatgi',
                'name_kn' => 'ಕಲಘಟಗಿ',
                'code' => 'KA_APMC_KLG_D',
                'district' => 'Dharwad',
                'market_type' => 'APMC',
                'lat' => 15.1800,
                'lon' => 74.9700,
                'address' => 'APMC Yard, Kalghatgi, Dharwad District',
                'raw_aliases' => ['KALGHATGI', 'KALAGHATAGI'],
            ],

            // ==========================================
            // GADAG (ಗದಗ)
            // ==========================================
            [
                'name' => 'Gadag',
                'name_kn' => 'ಗದಗ',
                'code' => 'KA_APMC_GDG',
                'district' => 'Gadag',
                'market_type' => 'APMC',
                'lat' => 15.4319,
                'lon' => 75.6358,
                'address' => 'APMC Yard, Gadag',
                'raw_aliases' => ['GADAG'],
            ],
            [
                'name' => 'Nargund',
                'name_kn' => 'ನರಗುಂದ',
                'code' => 'KA_APMC_NRG',
                'district' => 'Gadag',
                'market_type' => 'APMC',
                'lat' => 15.7200,
                'lon' => 75.3900,
                'address' => 'APMC Yard, Nargund, Gadag District',
                'raw_aliases' => ['NARGUND', 'NARAGUNDA'],
            ],
            [
                'name' => 'Laxmeshwar',
                'name_kn' => 'ಲಕ್ಷ್ಮೇಶ್ವರ',
                'code' => 'KA_APMC_LXM',
                'district' => 'Gadag',
                'market_type' => 'APMC',
                'lat' => 15.1300,
                'lon' => 75.4700,
                'address' => 'APMC Yard, Laxmeshwar, Gadag District',
                'raw_aliases' => ['LAXMESHWAR', 'LAKSHMESHWAR'],
            ],
            [
                'name' => 'Mundargi',
                'name_kn' => 'ಮುಂಡರಗಿ',
                'code' => 'KA_APMC_MND',
                'district' => 'Gadag',
                'market_type' => 'APMC',
                'lat' => 15.2100,
                'lon' => 75.8900,
                'address' => 'APMC Yard, Mundargi, Gadag District',
                'raw_aliases' => ['MUNDARGI', 'MUNDARAGI'],
            ],
            [
                'name' => 'Ron',
                'name_kn' => 'ರೋಣ',
                'code' => 'KA_APMC_RON',
                'district' => 'Gadag',
                'market_type' => 'APMC',
                'lat' => 15.7000,
                'lon' => 75.7300,
                'address' => 'APMC Yard, Ron, Gadag District',
                'raw_aliases' => ['RON'],
            ],

            // ==========================================
            // HAVERI (ಹಾವೇರಿ)
            // ==========================================
            [
                'name' => 'Haveri',
                'name_kn' => 'ಹಾವೇರಿ',
                'code' => 'KA_APMC_HVR',
                'district' => 'Haveri',
                'market_type' => 'APMC',
                'lat' => 14.7955,
                'lon' => 75.3991,
                'address' => 'APMC Yard, Haveri',
                'raw_aliases' => ['HAVERI'],
            ],
            [
                'name' => 'Ranebennur',
                'name_kn' => 'ರಾಣೆಬೆನ್ನೂರು',
                'code' => 'KA_APMC_RBN',
                'district' => 'Haveri',
                'market_type' => 'APMC',
                'lat' => 14.6230,
                'lon' => 75.6210,
                'address' => 'APMC Yard, Ranebennur, Haveri District',
                'raw_aliases' => ['RANIBENNUR', 'RANEBENNUR'],
            ],
            [
                'name' => 'Byadgi',
                'name_kn' => 'ಬ್ಯಾಡಗಿ (ಮೆಣಸಿನಕಾಯಿ ಮಾರುಕಟ್ಟೆ)',
                'code' => 'KA_APMC_BDG',
                'district' => 'Haveri',
                'market_type' => 'APMC',
                'lat' => 14.6800,
                'lon' => 75.4900,
                'address' => 'APMC Yard, Byadgi (Asia Renowned Chilli Market)',
                'raw_aliases' => ['BYADGI', 'BYADAGI'],
            ],
            [
                'name' => 'Hangal',
                'name_kn' => 'ಹಾನಗಲ್',
                'code' => 'KA_APMC_HGL',
                'district' => 'Haveri',
                'market_type' => 'APMC',
                'lat' => 14.7600,
                'lon' => 75.1300,
                'address' => 'APMC Yard, Hangal, Haveri District',
                'raw_aliases' => ['HANGAL'],
            ],
            [
                'name' => 'Hirekerur',
                'name_kn' => 'ಹಿರೇಕೆರೂರು',
                'code' => 'KA_APMC_HKR_H',
                'district' => 'Haveri',
                'market_type' => 'APMC',
                'lat' => 14.4600,
                'lon' => 75.3900,
                'address' => 'APMC Yard, Hirekerur, Haveri District',
                'raw_aliases' => ['HIREKERUR'],
            ],
            [
                'name' => 'Shiggaon',
                'name_kn' => 'ಶಿಗ್ಗಾವಿ',
                'code' => 'KA_APMC_SGN',
                'district' => 'Haveri',
                'market_type' => 'APMC',
                'lat' => 14.9900,
                'lon' => 75.2300,
                'address' => 'APMC Yard, Shiggaon, Haveri District',
                'raw_aliases' => ['SHIGGAON', 'SHIGGAVI'],
            ],
            [
                'name' => 'Savanur',
                'name_kn' => 'ಸವಣೂರು',
                'code' => 'KA_APMC_SVN',
                'district' => 'Haveri',
                'market_type' => 'APMC',
                'lat' => 14.9700,
                'lon' => 75.3400,
                'address' => 'APMC Yard, Savanur, Haveri District',
                'raw_aliases' => ['SAVANUR'],
            ],

            // ==========================================
            // BELAGAVI (ಬೆಳಗಾವಿ)
            // ==========================================
            [
                'name' => 'Belagavi',
                'name_kn' => 'ಬೆಳಗಾವಿ',
                'code' => 'KA_APMC_BLG',
                'district' => 'Belagavi',
                'market_type' => 'APMC',
                'lat' => 15.8497,
                'lon' => 74.4977,
                'address' => 'APMC Yard, Belagavi',
                'raw_aliases' => ['BELAGAVI', 'BELGAUM'],
            ],
            [
                'name' => 'Bailhongal',
                'name_kn' => 'ಬೈಲಹೊಂಗಲ',
                'code' => 'KA_APMC_BLH',
                'district' => 'Belagavi',
                'market_type' => 'APMC',
                'lat' => 15.8167,
                'lon' => 74.8667,
                'address' => 'APMC Yard, Bailhongal, Belagavi District',
                'raw_aliases' => ['BAILHONGAL', 'BAILAHONGALA'],
            ],
            [
                'name' => 'Gokak',
                'name_kn' => 'ಗೋಕಾಕ್',
                'code' => 'KA_APMC_GKK',
                'district' => 'Belagavi',
                'market_type' => 'APMC',
                'lat' => 16.1667,
                'lon' => 74.8333,
                'address' => 'APMC Yard, Gokak, Belagavi District',
                'raw_aliases' => ['GOKAK'],
            ],
            [
                'name' => 'Athani',
                'name_kn' => 'ಅಥಣಿ',
                'code' => 'KA_APMC_ATN',
                'district' => 'Belagavi',
                'market_type' => 'APMC',
                'lat' => 16.7330,
                'lon' => 75.0670,
                'address' => 'APMC Yard, Athani, Belagavi District',
                'raw_aliases' => ['ATHANI'],
            ],
            [
                'name' => 'Ramdurg',
                'name_kn' => 'ರಾಮದುರ್ಗ',
                'code' => 'KA_APMC_RMD',
                'district' => 'Belagavi',
                'market_type' => 'APMC',
                'lat' => 15.9500,
                'lon' => 75.3000,
                'address' => 'APMC Yard, Ramdurg, Belagavi District',
                'raw_aliases' => ['RAMDURGA', 'RAMDURG'],
            ],
            [
                'name' => 'Savadatti',
                'name_kn' => 'ಸವದತ್ತಿ',
                'code' => 'KA_APMC_SVD',
                'district' => 'Belagavi',
                'market_type' => 'APMC',
                'lat' => 15.7700,
                'lon' => 75.1200,
                'address' => 'APMC Yard, Savadatti, Belagavi District',
                'raw_aliases' => ['SAVADATTI', 'SAUNDATTI'],
            ],
            [
                'name' => 'Sankeshwar',
                'name_kn' => 'ಸಂಕೇಶ್ವರ',
                'code' => 'KA_APMC_SNK',
                'district' => 'Belagavi',
                'market_type' => 'APMC',
                'lat' => 16.2600,
                'lon' => 74.4800,
                'address' => 'APMC Yard, Sankeshwar, Belagavi District',
                'raw_aliases' => ['SANKESHWAR'],
            ],
            [
                'name' => 'Nippani',
                'name_kn' => 'ನಿಪ್ಪಾಣಿ',
                'code' => 'KA_APMC_NPN',
                'district' => 'Belagavi',
                'market_type' => 'APMC',
                'lat' => 16.4000,
                'lon' => 74.3800,
                'address' => 'APMC Yard, Nippani, Belagavi District',
                'raw_aliases' => ['NIPPANI', 'NIPANI'],
            ],
            [
                'name' => 'Kudchi',
                'name_kn' => 'ಕುಡಚಿ',
                'code' => 'KA_APMC_KDC',
                'district' => 'Belagavi',
                'market_type' => 'APMC',
                'lat' => 16.6300,
                'lon' => 74.8500,
                'address' => 'APMC Yard, Kudchi, Belagavi District',
                'raw_aliases' => ['KUDCHI'],
            ],
            [
                'name' => 'Nandagad',
                'name_kn' => 'ನಂದಗಡ',
                'code' => 'KA_APMC_NDG',
                'district' => 'Belagavi',
                'market_type' => 'APMC',
                'lat' => 15.5500,
                'lon' => 74.5500,
                'address' => 'APMC Yard, Nandagad, Belagavi District',
                'raw_aliases' => ['NANDAGAD', 'NANDAGADA'],
            ],
            [
                'name' => 'Yaragatti',
                'name_kn' => 'ಯರಗಟ್ಟಿ',
                'code' => 'KA_APMC_YRG',
                'district' => 'Belagavi',
                'market_type' => 'APMC',
                'lat' => 15.9300,
                'lon' => 75.0200,
                'address' => 'APMC Yard, Yaragatti, Belagavi District',
                'raw_aliases' => ['YARAGATTI'],
            ],

            // ==========================================
            // BAGALKOTE (ಬಾಗಲಕೋಟೆ)
            // ==========================================
            [
                'name' => 'Bagalkot',
                'name_kn' => 'ಬಾಗಲಕೋಟೆ',
                'code' => 'KA_APMC_BGK',
                'district' => 'Bagalkote',
                'market_type' => 'APMC',
                'lat' => 16.1817,
                'lon' => 75.6958,
                'address' => 'APMC Yard, Bagalkot',
                'raw_aliases' => ['BAGALKOT', 'BAGALKOTE'],
            ],
            [
                'name' => 'Jamkandi',
                'name_kn' => 'ಜಮಖಂಡಿ',
                'code' => 'KA_APMC_JMK',
                'district' => 'Bagalkote',
                'market_type' => 'APMC',
                'lat' => 16.5050,
                'lon' => 75.2950,
                'address' => 'APMC Yard, Jamkandi, Bagalkote District',
                'raw_aliases' => ['JAMKANDI', 'JAMKHANDI'],
            ],
            [
                'name' => 'Badami',
                'name_kn' => 'ಬಾದಾಮಿ',
                'code' => 'KA_APMC_BDM',
                'district' => 'Bagalkote',
                'market_type' => 'APMC',
                'lat' => 15.9180,
                'lon' => 75.6760,
                'address' => 'APMC Yard, Badami, Bagalkote District',
                'raw_aliases' => ['BADAMI'],
            ],
            [
                'name' => 'Hungund',
                'name_kn' => 'ಹುನಗುಂದ',
                'code' => 'KA_APMC_HGD',
                'district' => 'Bagalkote',
                'market_type' => 'APMC',
                'lat' => 16.0640,
                'lon' => 76.0570,
                'address' => 'APMC Yard, Hungund, Bagalkote District',
                'raw_aliases' => ['HUNGUND', 'HUNAGUNDA'],
            ],

            // ==========================================
            // VIJAYAPURA (ವಿಜಯಪುರ)
            // ==========================================
            [
                'name' => 'Vijayapura',
                'name_kn' => 'ವಿಜಯಪುರ',
                'code' => 'KA_APMC_VJP',
                'district' => 'Vijayapura',
                'market_type' => 'APMC',
                'lat' => 16.8302,
                'lon' => 75.7100,
                'address' => 'APMC Yard, Vijayapura',
                'raw_aliases' => ['VIJAYAPURA', 'BIJAPUR'],
            ],
            [
                'name' => 'Talikote',
                'name_kn' => 'ತಾಳಿಕೋಟೆ',
                'code' => 'KA_APMC_TLK',
                'district' => 'Vijayapura',
                'market_type' => 'APMC',
                'lat' => 16.4800,
                'lon' => 76.3100,
                'address' => 'APMC Yard, Talikote, Vijayapura District',
                'raw_aliases' => ['TALIKOTE', 'TALIKOTI'],
            ],
            [
                'name' => 'Sindagi',
                'name_kn' => 'ಸಿಂದಗಿ',
                'code' => 'KA_APMC_SDG_V',
                'district' => 'Vijayapura',
                'market_type' => 'APMC',
                'lat' => 16.9200,
                'lon' => 76.2300,
                'address' => 'APMC Yard, Sindagi, Vijayapura District',
                'raw_aliases' => ['SINDAGI', 'SINDHAGI'],
            ],

            // ==========================================
            // KALABURAGI (ಕಲಬುರಗಿ)
            // ==========================================
            [
                'name' => 'Kalaburagi (Tur Market)',
                'name_kn' => 'ಕಲಬುರಗಿ (ತೊಗರಿ ಮಾರುಕಟ್ಟೆ)',
                'code' => 'KA_APMC_KLB',
                'district' => 'Kalaburagi',
                'market_type' => 'APMC',
                'lat' => 17.3297,
                'lon' => 76.8343,
                'address' => 'Nehru Gunj APMC Yard, Kalaburagi (Red Gram Capital)',
                'raw_aliases' => ['KALABURAGI', 'GULBARGA', 'NEHRU GUNJ'],
            ],
            [
                'name' => 'Sedam',
                'name_kn' => 'ಸೇಡಂ',
                'code' => 'KA_APMC_SDM',
                'district' => 'Kalaburagi',
                'market_type' => 'APMC',
                'lat' => 17.1800,
                'lon' => 77.2900,
                'address' => 'APMC Yard, Sedam, Kalaburagi District',
                'raw_aliases' => ['SEDAM'],
            ],
            [
                'name' => 'Chittapur',
                'name_kn' => 'ಚಿತ್ತಾಪುರ',
                'code' => 'KA_APMC_CTP',
                'district' => 'Kalaburagi',
                'market_type' => 'APMC',
                'lat' => 17.1200,
                'lon' => 76.9600,
                'address' => 'APMC Yard, Chittapur, Kalaburagi District',
                'raw_aliases' => ['CHITTAPURA', 'CHITTAPUR'],
            ],
            [
                'name' => 'Chincholi',
                'name_kn' => 'ಚಿಂಚೋಳಿ',
                'code' => 'KA_APMC_CNC',
                'district' => 'Kalaburagi',
                'market_type' => 'APMC',
                'lat' => 17.4700,
                'lon' => 77.4300,
                'address' => 'APMC Yard, Chincholi, Kalaburagi District',
                'raw_aliases' => ['CHINCOLI', 'CHINCHOLI'],
            ],
            [
                'name' => 'Jevargi',
                'name_kn' => 'ಜೇವರ್ಗಿ',
                'code' => 'KA_APMC_JVR',
                'district' => 'Kalaburagi',
                'market_type' => 'APMC',
                'lat' => 17.0200,
                'lon' => 76.7700,
                'address' => 'APMC Yard, Jevargi, Kalaburagi District',
                'raw_aliases' => ['JEVARGI', 'JEVARAGI'],
            ],

            // ==========================================
            // BIDAR (ಬೀದರ್)
            // ==========================================
            [
                'name' => 'Bidar',
                'name_kn' => 'ಬೀದರ್',
                'code' => 'KA_APMC_BDR',
                'district' => 'Bidar',
                'market_type' => 'APMC',
                'lat' => 17.9104,
                'lon' => 77.5199,
                'address' => 'APMC Yard, Bidar',
                'raw_aliases' => ['BIDAR'],
            ],
            [
                'name' => 'Basavakalyana',
                'name_kn' => 'ಬಸವಕಲ್ಯಾಣ',
                'code' => 'KA_APMC_BSK',
                'district' => 'Bidar',
                'market_type' => 'APMC',
                'lat' => 17.8700,
                'lon' => 76.9500,
                'address' => 'APMC Yard, Basavakalyana, Bidar District',
                'raw_aliases' => ['BASAVAKALYANA', 'BASAVAKALYAN'],
            ],
            [
                'name' => 'Bhalki',
                'name_kn' => 'ಭಾಲ್ಕಿ',
                'code' => 'KA_APMC_BLK',
                'district' => 'Bidar',
                'market_type' => 'APMC',
                'lat' => 18.0400,
                'lon' => 77.2100,
                'address' => 'APMC Yard, Bhalki, Bidar District',
                'raw_aliases' => ['BHALKI'],
            ],
            [
                'name' => 'Aurad',
                'name_kn' => 'ಔರಾದ್',
                'code' => 'KA_APMC_ARD',
                'district' => 'Bidar',
                'market_type' => 'APMC',
                'lat' => 18.2500,
                'lon' => 77.4300,
                'address' => 'APMC Yard, Aurad, Bidar District',
                'raw_aliases' => ['AURAD'],
            ],

            // ==========================================
            // RAICHUR (ರಾಯಚೂರು)
            // ==========================================
            [
                'name' => 'Raichur (Cotton & Paddy)',
                'name_kn' => 'ರಾಯಚೂರು (ಹತ್ತಿ ಮತ್ತು ಭತ್ತ)',
                'code' => 'KA_APMC_RCH',
                'district' => 'Raichur',
                'market_type' => 'APMC',
                'lat' => 16.2076,
                'lon' => 77.3463,
                'address' => 'APMC Yard, Raichur',
                'raw_aliases' => ['RAICHUR'],
            ],
            [
                'name' => 'Sindhanur',
                'name_kn' => 'ಸಿಂಧನೂರು (ಭತ್ತದ ರಾಜಧಾನಿ)',
                'code' => 'KA_APMC_SDN',
                'district' => 'Raichur',
                'market_type' => 'APMC',
                'lat' => 15.7700,
                'lon' => 76.7600,
                'address' => 'APMC Yard, Sindhanur (Paddy Capital)',
                'raw_aliases' => ['SINDHANUR'],
            ],
            [
                'name' => 'Manvi',
                'name_kn' => 'ಮಾನ್ವಿ',
                'code' => 'KA_APMC_MNV',
                'district' => 'Raichur',
                'market_type' => 'APMC',
                'lat' => 15.9900,
                'lon' => 77.0500,
                'address' => 'APMC Yard, Manvi, Raichur District',
                'raw_aliases' => ['MANVI'],
            ],
            [
                'name' => 'Lingasugur',
                'name_kn' => 'ಲಿಂಗಸುಗೂರು',
                'code' => 'KA_APMC_LSG',
                'district' => 'Raichur',
                'market_type' => 'APMC',
                'lat' => 16.1600,
                'lon' => 76.5200,
                'address' => 'APMC Yard, Lingasugur, Raichur District',
                'raw_aliases' => ['LINGASARGUR', 'LINGASUGUR'],
            ],
            [
                'name' => 'Maski',
                'name_kn' => 'ಮಸ್ಕಿ',
                'code' => 'KA_APMC_MSK',
                'district' => 'Raichur',
                'market_type' => 'APMC',
                'lat' => 15.9600,
                'lon' => 76.6600,
                'address' => 'APMC Yard, Maski, Raichur District',
                'raw_aliases' => ['MASKI'],
            ],

            // ==========================================
            // KOPPAL (ಕೊಪ್ಪಳ)
            // ==========================================
            [
                'name' => 'Koppal',
                'name_kn' => 'ಕೊಪ್ಪಳ',
                'code' => 'KA_APMC_KPL',
                'district' => 'Koppal',
                'market_type' => 'APMC',
                'lat' => 15.3456,
                'lon' => 76.1557,
                'address' => 'APMC Yard, Koppal',
                'raw_aliases' => ['KOPPAL'],
            ],
            [
                'name' => 'Gangavati',
                'name_kn' => 'ಗಂಗಾವತಿ (ಭತ್ತದ ಮಾರುಕಟ್ಟೆ)',
                'code' => 'KA_APMC_GGV',
                'district' => 'Koppal',
                'market_type' => 'APMC',
                'lat' => 15.4300,
                'lon' => 76.5300,
                'address' => 'APMC Yard, Gangavati (Rice Bowl of Karnataka)',
                'raw_aliases' => ['GANGAVATI', 'GANGAVATHI'],
            ],
            [
                'name' => 'Kushtagi',
                'name_kn' => 'ಕುಷ್ಟಗಿ',
                'code' => 'KA_APMC_KSG',
                'district' => 'Koppal',
                'market_type' => 'APMC',
                'lat' => 15.7500,
                'lon' => 76.2000,
                'address' => 'APMC Yard, Kushtagi, Koppal District',
                'raw_aliases' => ['KUSTAGI', 'KUSHTAGI'],
            ],
            [
                'name' => 'Yelburga',
                'name_kn' => 'ಯಲಬುರ್ಗಾ',
                'code' => 'KA_APMC_YBG',
                'district' => 'Koppal',
                'market_type' => 'APMC',
                'lat' => 15.6300,
                'lon' => 76.0100,
                'address' => 'APMC Yard, Yelburga, Koppal District',
                'raw_aliases' => ['YELBURGA', 'YALABURGA'],
            ],
            [
                'name' => 'Kanakagiri',
                'name_kn' => 'ಕನಕಗಿರಿ',
                'code' => 'KA_APMC_KKG',
                'district' => 'Koppal',
                'market_type' => 'APMC',
                'lat' => 15.5700,
                'lon' => 76.4200,
                'address' => 'APMC Yard, Kanakagiri, Koppal District',
                'raw_aliases' => ['KANAKAGIRI'],
            ],
            [
                'name' => 'Karatagi',
                'name_kn' => 'ಕಾರಟಗಿ',
                'code' => 'KA_APMC_KTG',
                'district' => 'Koppal',
                'market_type' => 'APMC',
                'lat' => 15.5700,
                'lon' => 76.6800,
                'address' => 'APMC Yard, Karatagi, Koppal District',
                'raw_aliases' => ['KARTAGI', 'KARATAGI'],
            ],

            // ==========================================
            // BALLARI (ಬಳ್ಳಾರಿ)
            // ==========================================
            [
                'name' => 'Ballari',
                'name_kn' => 'ಬಳ್ಳಾರಿ',
                'code' => 'KA_APMC_BAL',
                'district' => 'Ballari',
                'market_type' => 'APMC',
                'lat' => 15.1394,
                'lon' => 76.9214,
                'address' => 'APMC Yard, Ballari',
                'raw_aliases' => ['BALLARI', 'BELLARY'],
            ],
            [
                'name' => 'Kampli',
                'name_kn' => 'ಕಂಪ್ಲಿ',
                'code' => 'KA_APMC_KMP',
                'district' => 'Ballari',
                'market_type' => 'APMC',
                'lat' => 15.4050,
                'lon' => 76.5950,
                'address' => 'APMC Yard, Kampli, Ballari District',
                'raw_aliases' => ['KAMPLI'],
            ],
            [
                'name' => 'Siruguppa',
                'name_kn' => 'ಸಿರಗುಪ್ಪ',
                'code' => 'KA_APMC_SGP',
                'district' => 'Ballari',
                'market_type' => 'APMC',
                'lat' => 15.6320,
                'lon' => 76.8970,
                'address' => 'APMC Yard, Siruguppa, Ballari District',
                'raw_aliases' => ['SIRAGUPPA', 'SIRUGUPPA'],
            ],

            // ==========================================
            // VIJAYANAGARA (ವಿಜಯನಗರ)
            // ==========================================
            [
                'name' => 'Hosapete',
                'name_kn' => 'ಹೊಸಪೇಟೆ',
                'code' => 'KA_APMC_HSP',
                'district' => 'Vijayanagara',
                'market_type' => 'APMC',
                'lat' => 15.2700,
                'lon' => 76.3900,
                'address' => 'APMC Yard, Hosapete',
                'raw_aliases' => ['HOSAPETE', 'HOSPET'],
            ],
            [
                'name' => 'Harapanahalli',
                'name_kn' => 'ಹರಪನಹಳ್ಳಿ',
                'code' => 'KA_APMC_HPH',
                'district' => 'Vijayanagara',
                'market_type' => 'APMC',
                'lat' => 14.7900,
                'lon' => 75.9900,
                'address' => 'APMC Yard, Harapanahalli, Vijayanagara District',
                'raw_aliases' => ['HARAPANAHALLI'],
            ],
            [
                'name' => 'Hagaribommanahalli',
                'name_kn' => 'ಹಗರಿಬೊಮ್ಮನಹಳ್ಳಿ',
                'code' => 'KA_APMC_HBH',
                'district' => 'Vijayanagara',
                'market_type' => 'APMC',
                'lat' => 15.0800,
                'lon' => 76.2000,
                'address' => 'APMC Yard, Hagaribommanahalli, Vijayanagara District',
                'raw_aliases' => ['HAGARI BOMMANA HALLI', 'HAGARIBOMMANAHALLI', 'H.B.HALLI'],
            ],
            [
                'name' => 'Hoovinahadagali',
                'name_kn' => 'ಹೂವಿನಹಡಗಲಿ',
                'code' => 'KA_APMC_HHD',
                'district' => 'Vijayanagara',
                'market_type' => 'APMC',
                'lat' => 15.0200,
                'lon' => 75.9500,
                'address' => 'APMC Yard, Hoovinahadagali, Vijayanagara District',
                'raw_aliases' => ['HOOVINAHADAGALI', 'HADAGALI'],
            ],
            [
                'name' => 'Kottur',
                'name_kn' => 'ಕೊಟ್ಟೂರು',
                'code' => 'KA_APMC_KTR',
                'district' => 'Vijayanagara',
                'market_type' => 'APMC',
                'lat' => 14.9300,
                'lon' => 76.2200,
                'address' => 'APMC Yard, Kottur, Vijayanagara District',
                'raw_aliases' => ['KOTTUR', 'KOTTURU'],
            ],

            // ==========================================
            // YADGIR (ಯಾದಗಿರಿ)
            // ==========================================
            [
                'name' => 'Yadgir',
                'name_kn' => 'ಯಾದಗಿರಿ',
                'code' => 'KA_APMC_YDG',
                'district' => 'Yadgir',
                'market_type' => 'APMC',
                'lat' => 16.7700,
                'lon' => 77.1300,
                'address' => 'APMC Yard, Yadgir',
                'raw_aliases' => ['YADGIR', 'YADAGIRI'],
            ],

            // ==========================================
            // KODAGU (ಕೊಡಗು)
            // ==========================================
            [
                'name' => 'Madikeri Market',
                'name_kn' => 'ಮಡಿಕೇರಿ ಮಾರುಕಟ್ಟೆ',
                'code' => 'KA_MKT_MDK',
                'district' => 'Kodagu',
                'market_type' => 'APMC',
                'lat' => 12.4244,
                'lon' => 75.7382,
                'address' => 'APMC Market Yard, Madikeri, Kodagu',
                'raw_aliases' => ['MADIKERI', 'MERCARA'],
            ],
            [
                'name' => 'Somwarpet',
                'name_kn' => 'ಸೋಮವಾರಪೇಟೆ',
                'code' => 'KA_APMC_SWP',
                'district' => 'Kodagu',
                'market_type' => 'APMC',
                'lat' => 12.6000,
                'lon' => 75.8600,
                'address' => 'APMC Yard, Somwarpet, Kodagu District',
                'raw_aliases' => ['SOMWARPET', 'SOMAVARAPETE'],
            ],
            [
                'name' => 'Gonikoppal',
                'name_kn' => 'ಗೋಣಿಕೊಪ್ಪಲು',
                'code' => 'KA_APMC_GNK',
                'district' => 'Kodagu',
                'market_type' => 'APMC',
                'lat' => 12.1800,
                'lon' => 75.9300,
                'address' => 'APMC Yard, Gonikoppal, Kodagu District',
                'raw_aliases' => ['GONIKOPPAL', 'GONIKOPPA'],
            ],

            // ==========================================
            // ADDITIONAL KRAMA APMC MARKETS
            // ==========================================
            [
                'name' => 'Afzalpur',
                'name_kn' => 'ಅಫಜಲಪುರ',
                'code' => 'KA_APMC_AFZ',
                'district' => 'Kalaburagi',
                'market_type' => 'APMC',
                'lat' => 17.2000,
                'lon' => 76.3500,
                'address' => 'APMC Market Yard, Afzalpur, Kalaburagi District',
                'raw_aliases' => ['AFZALPUR'],
            ],
            [
                'name' => 'Aland',
                'name_kn' => 'ಆಳಂದ',
                'code' => 'KA_APMC_ALN',
                'district' => 'Kalaburagi',
                'market_type' => 'APMC',
                'lat' => 17.5667,
                'lon' => 76.5667,
                'address' => 'APMC Market Yard, Aland, Kalaburagi District',
                'raw_aliases' => ['ALANDA', 'ALAND'],
            ],
            [
                'name' => 'Bilagi',
                'name_kn' => 'ಬೀಳಗಿ',
                'code' => 'KA_APMC_BLI',
                'district' => 'Bagalkote',
                'market_type' => 'APMC',
                'lat' => 16.3486,
                'lon' => 75.6186,
                'address' => 'APMC Market Yard, Bilagi, Bagalkote District',
                'raw_aliases' => ['BILAGI'],
            ],
            [
                'name' => 'Devadurga',
                'name_kn' => 'ದೇವದುರ್ಗ',
                'code' => 'KA_APMC_DVD',
                'district' => 'Raichur',
                'market_type' => 'APMC',
                'lat' => 16.4258,
                'lon' => 76.9381,
                'address' => 'APMC Market Yard, Devadurga, Raichur District',
                'raw_aliases' => ['DEVDURGA', 'DEVADURGA'],
            ],
            [
                'name' => 'Indi',
                'name_kn' => 'ಇಂಡಿ',
                'code' => 'KA_APMC_IND',
                'district' => 'Vijayapura',
                'market_type' => 'APMC',
                'lat' => 17.1819,
                'lon' => 75.9619,
                'address' => 'APMC Market Yard, Indi, Vijayapura District',
                'raw_aliases' => ['ENDI', 'INDI'],
            ],
            [
                'name' => 'Humnabad',
                'name_kn' => 'ಹುಮನಾಬಾದ್',
                'code' => 'KA_APMC_HMN',
                'district' => 'Bidar',
                'market_type' => 'APMC',
                'lat' => 17.7667,
                'lon' => 77.1333,
                'address' => 'APMC Market Yard, Humnabad, Bidar District',
                'raw_aliases' => ['HUMNABAD'],
            ],
            [
                'name' => 'KGF',
                'name_kn' => 'ಕೆ.ಜಿ.ಎಫ್.',
                'code' => 'KA_APMC_KGF',
                'district' => 'Kolar',
                'market_type' => 'APMC',
                'lat' => 12.9600,
                'lon' => 78.2700,
                'address' => 'APMC Market Yard, KGF, Kolar District',
                'raw_aliases' => ['K.G.F.', 'KGF', 'K.G.F'],
            ],
            [
                'name' => 'Kudligi',
                'name_kn' => 'ಕೂಡ್ಲಿಗಿ',
                'code' => 'KA_APMC_KDL',
                'district' => 'Vijayanagara',
                'market_type' => 'APMC',
                'lat' => 14.9000,
                'lon' => 76.3833,
                'address' => 'APMC Market Yard, Kudligi, Vijayanagara District',
                'raw_aliases' => ['KUDLIGI'],
            ],
            [
                'name' => 'Kunigal',
                'name_kn' => 'ಕುಣಿಗಲ್',
                'code' => 'KA_APMC_KNG',
                'district' => 'Tumakuru',
                'market_type' => 'APMC',
                'lat' => 13.0200,
                'lon' => 77.0300,
                'address' => 'APMC Market Yard, Kunigal, Tumakuru District',
                'raw_aliases' => ['KUNIGAL'],
            ],
            [
                'name' => 'Madhugiri',
                'name_kn' => 'ಮಧುಗಿರಿ',
                'code' => 'KA_APMC_MDG',
                'district' => 'Tumakuru',
                'market_type' => 'APMC',
                'lat' => 13.6600,
                'lon' => 77.2100,
                'address' => 'APMC Market Yard, Madhugiri, Tumakuru District',
                'raw_aliases' => ['MADHUGIRI'],
            ],
            [
                'name' => 'Mahalingpur',
                'name_kn' => 'ಮಹಾಲಿಂಗಪುರ',
                'code' => 'KA_APMC_MHL',
                'district' => 'Bagalkote',
                'market_type' => 'APMC',
                'lat' => 16.3833,
                'lon' => 75.1167,
                'address' => 'APMC Market Yard, Mahalingpur, Bagalkote District',
                'raw_aliases' => ['MAHALINGAPURA', 'MAHALINGPUR'],
            ],
            [
                'name' => 'Mudhol',
                'name_kn' => 'ಮುಧೋಳ',
                'code' => 'KA_APMC_MDL',
                'district' => 'Bagalkote',
                'market_type' => 'APMC',
                'lat' => 16.3500,
                'lon' => 75.2833,
                'address' => 'APMC Market Yard, Mudhol, Bagalkote District',
                'raw_aliases' => ['MUDHOL'],
            ],
            [
                'name' => 'Pavagada',
                'name_kn' => 'ಪಾವಗಡ',
                'code' => 'KA_APMC_PVG',
                'district' => 'Tumakuru',
                'market_type' => 'APMC',
                'lat' => 14.1000,
                'lon' => 77.2800,
                'address' => 'APMC Market Yard, Pavagada, Tumakuru District',
                'raw_aliases' => ['PAVAGADA'],
            ],
            [
                'name' => 'Rampura',
                'name_kn' => 'ರಾಂಪುರ',
                'code' => 'KA_APMC_RMP',
                'district' => 'Chitradurga',
                'market_type' => 'APMC',
                'lat' => 14.8667,
                'lon' => 76.8167,
                'address' => 'APMC Market Yard, Rampura, Chitradurga District',
                'raw_aliases' => ['RAMPURA'],
            ],
            [
                'name' => 'Sandur',
                'name_kn' => 'ಸಂಡೂರು',
                'code' => 'KA_APMC_SND',
                'district' => 'Ballari',
                'market_type' => 'APMC',
                'lat' => 15.0833,
                'lon' => 76.5500,
                'address' => 'APMC Market Yard, Sandur, Ballari District',
                'raw_aliases' => ['SANDUR'],
            ],
            [
                'name' => 'Shahapur',
                'name_kn' => 'ಶಹಾಪುರ',
                'code' => 'KA_APMC_SHP',
                'district' => 'Yadgir',
                'market_type' => 'APMC',
                'lat' => 16.7000,
                'lon' => 76.8333,
                'address' => 'APMC Market Yard, Shahapur, Yadgir District',
                'raw_aliases' => ['SHAHAPUR'],
            ],
            [
                'name' => 'Shorapur',
                'name_kn' => 'ಶೋರಾಪುರ',
                'code' => 'KA_APMC_SRP',
                'district' => 'Yadgir',
                'market_type' => 'APMC',
                'lat' => 16.5167,
                'lon' => 76.7500,
                'address' => 'APMC Market Yard, Shorapur, Yadgir District',
                'raw_aliases' => ['SHORAPUR'],
            ],

            // ==========================================
            // COMMODITY BOARDS & SPECIALIZED CENTRES
            // ==========================================
            [
                'name' => 'Madikeri (Coffee Board Centre)',
                'name_kn' => 'ಮಡಿಕೇರಿ (ಕಾಫಿ ಮಂಡಳಿ ಕೇಂದ್ರ)',
                'code' => 'CB_MDK',
                'district' => 'Kodagu',
                'market_type' => 'Private',
                'lat' => 12.4244,
                'lon' => 75.7382,
                'address' => 'Coffee Board Regional Office, Madikeri',
                'raw_aliases' => ['MADIKERI COFFEE BOARD', 'COFFEE BOARD MADIKERI'],
            ],
            [
                'name' => 'Chikkamagaluru (Coffee Board Centre)',
                'name_kn' => 'ಚಿಕ್ಕಮಗಳೂರು (ಕಾಫಿ ಮಂಡಳಿ ಕೇಂದ್ರ)',
                'code' => 'CB_CKM',
                'district' => 'Chikkamagaluru',
                'market_type' => 'Private',
                'lat' => 13.3161,
                'lon' => 75.7720,
                'address' => 'Coffee Board Office, Chikkamagaluru',
                'raw_aliases' => ['CHIKKAMAGALURU COFFEE BOARD', 'COFFEE BOARD CHIKKAMAGALURU'],
            ],
            [
                'name' => 'Hassan (Coffee Board Centre)',
                'name_kn' => 'ಹಾಸನ (ಕಾಫಿ ಮಂಡಳಿ ಕೇಂದ್ರ)',
                'code' => 'CB_HSN',
                'district' => 'Hassan',
                'market_type' => 'Private',
                'lat' => 13.0033,
                'lon' => 76.1004,
                'address' => 'Coffee Board Office, B.M. Road, Hassan',
                'raw_aliases' => ['HASSAN COFFEE BOARD', 'COFFEE BOARD HASSAN'],
            ],
            [
                'name' => 'Arsikere (CDB Centre)',
                'name_kn' => 'ಅರಸೀಕೆರೆ (ತೆಂಗು ಮಂಡಳಿ ಕೇಂದ್ರ)',
                'code' => 'CDB_ASK',
                'district' => 'Hassan',
                'market_type' => 'Private',
                'lat' => 13.3138,
                'lon' => 76.2570,
                'address' => 'Coconut Development Board Field Office, Arsikere',
                'raw_aliases' => ['ARSIKERE CDB', 'ARSIKERE COCONUT BOARD'],
            ],
            [
                'name' => 'Mandya (CDB Centre)',
                'name_kn' => 'ಮಂಡ್ಯ (ತೆಂಗು ಮಂಡಳಿ ಕೇಂದ್ರ)',
                'code' => 'CDB_MDY',
                'district' => 'Mandya',
                'market_type' => 'Private',
                'lat' => 12.5218,
                'lon' => 76.8951,
                'address' => 'Coconut Development Board Office, Mandya',
                'raw_aliases' => ['MANDYA CDB', 'MANDYA COCONUT BOARD'],
            ],
            [
                'name' => 'Tumakuru (CDB Centre)',
                'name_kn' => 'ತುಮಕೂರು (ತೆಂಗು ಮಂಡಳಿ ಕೇಂದ್ರ)',
                'code' => 'CDB_TMK',
                'district' => 'Tumakuru',
                'market_type' => 'Private',
                'lat' => 13.3409,
                'lon' => 77.1010,
                'address' => 'Coconut Development Board Office, Tumakuru',
                'raw_aliases' => ['TUMAKURU CDB', 'TUMAKURU COCONUT BOARD'],
            ],
            [
                'name' => 'Tiptur (CDB Centre)',
                'name_kn' => 'ತಿಪಟೂರು (ತೆಂಗು ಮಂಡಳಿ ಕೇಂದ್ರ)',
                'code' => 'CDB_TPT',
                'district' => 'Tumakuru',
                'market_type' => 'Private',
                'lat' => 13.2570,
                'lon' => 76.4780,
                'address' => 'Coconut Development Board Office, Tiptur',
                'raw_aliases' => ['TIPTUR CDB', 'TIPTUR COCONUT BOARD'],
            ],
        ];
    }
}
